SpiNNakerManchester/sPyNNaker

- spynnaker/pyNN/spinnaker.py
- spynnaker/pyNN/spynnaker_comms_functions.py
- spynnaker/pyNN/utilities/reports.py
adds a provance report (currently only has routing diagnostics). The report is in XML so that it can be used in big data stuff more easily. (theres a possible debate of putting it as a ontology, but i cant be bothered to do that jsut yet)
> added a xml doc for routing diagnostics for easy usage of debugging

- spynnaker/pyNN/models/abstract_models/abstract_population_recordable_vertex.py
- spynnaker/pyNN/models/abstract_models/abstract_population_vertex.py
This again gives a pretty massive speedup
> Optimise getspikes

- spynnaker/pyNN/models/abstract_models/abstract_population_recordable_vertex.py
- spynnaker/pyNN/models/abstract_models/abstract_population_vertex.py
Reverts SpiNNakerManchester/sPyNNaker#98
when running synfire chain, this failed. dont know why. jamie. pelase fix.
> Revert "Optimise getspikes"

- spynnaker/pyNN/__init__.py
- spynnaker/pyNN/spinnaker.py
- spynnaker/pyNN/utilities/database/socket_address.py
- spynnaker/spynnaker.cfg
fixes to remove databse options
annoyingly it seems pycharm isnt perfect for brnaches. so this is the only modules whos brnaches is not in master already. ggrrgle
> fixes for the new databse options

- spynnaker/pyNN/models/pynn_population.py
fixes simons issue on get v hanging when record not set properly
> fix get v issue

- spynnaker/pyNN/spinnaker.py
Fixes issues with SpiNNakerLink functionality
> Fix spinnaker links

- neural_modelling/src/Makefile.common
- neural_modelling/src/delay_extension/Makefile
- neural_modelling/src/neuron/builds/IF_cond_exp/Makefile
- neural_modelling/src/neuron/builds/IF_cond_exp_stdp_mad_nearest_pair_additive/Makefile
- neural_modelling/src/neuron/builds/IF_cond_exp_stdp_mad_pair_additive/Makefile
- neural_modelling/src/neuron/builds/IF_curr_exp/Makefile
- neural_modelling/src/neuron/builds/IF_curr_exp_dual/Makefile
- neural_modelling/src/neuron/builds/IF_curr_exp_stdp_mad_nearest_pair_additive/Makefile
- neural_modelling/src/neuron/builds/IF_curr_exp_stdp_mad_nearest_pair_multiplicative/Makefile
- neural_modelling/src/neuron/builds/IF_curr_exp_stdp_mad_pair_additive/Makefile
- neural_modelling/src/neuron/builds/IF_curr_exp_stdp_mad_pair_multiplicative/Makefile
- neural_modelling/src/neuron/builds/IF_curr_exp_stdp_mad_pfister_triplet_additive/Makefile
- neural_modelling/src/neuron/builds/IF_curr_exp_stdp_nearest_pair_additive/Makefile
- neural_modelling/src/neuron/builds/IF_curr_exp_stdp_nearest_pair_multiplicative/Makefile
- neural_modelling/src/neuron/builds/IF_curr_exp_stdp_pair_additive/Makefile
- neural_modelling/src/neuron/builds/IF_curr_exp_stdp_pair_multiplicative/Makefile
- neural_modelling/src/neuron/builds/IF_curr_exp_stdp_pfister_triplet_additive/Makefile
- neural_modelling/src/neuron/builds/IZK_cond_exp/Makefile
- neural_modelling/src/neuron/builds/IZK_curr_exp/Makefile
- neural_modelling/src/neuron/builds/Makefile.common
- neural_modelling/src/spike_source/poisson/Makefile
- spynnaker/pyNN/models/neuron/additional_inputs/abstract_additional_input.py
Simplification and enhancement of the Makefiles
Note the main change is the need to specify the sources as .c rather than .o (which makes more sense)
This should also support multiple source directories (rather than just 2 currently supported)
This pull request is mainly for notification of the change, and will be merged immediately as it is needed for the release
> Makefile fixes

- neural_modelling/src/neuron/builds/Makefile.common
- neural_modelling/src/neuron/plasticity/common/post_events.h
- neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
Some fixes that Jamie has made (that should have been in already), and some Makefile fixes.
> Stdp fixes

- spynnaker/pyNN/overridden_pacman_functions/algorithms_metadata.xml
- spynnaker/pyNN/overridden_pacman_functions/spynnaker_data_specification_writer.py
> measure dsg memory

- neural_modelling/src/neuron/c_main.c
- neural_modelling/src/spike_source/poisson/spike_source_poisson.c
Called recording reset instead of recording initialize during a reset
> Recording reset

- spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
simple fix found ad given by @rowleya
> get-spikes was using enum inestead of enum.value

- spynnaker/pyNN/__init__.py
tiny update to improve logging
> fixed warning on extra parameters

- .gitattributes
See https://github.com/github/linguist#overrides
See https://github.com/github/linguist/issues/1626
> Make github detect what language our C is (!)

- neural_modelling/src/Makefile.common
Should we do the same in spinnaker_tools?
> check NEURAL_MODELLING_DIRS is completely correct

- spynnaker/pyNN/models/spike_source/spike_source_array.py
fixes issue with SSA and describe
> added describe to SSA

- spynnaker/pyNN/models/spike_source/spike_source_poisson.py
Fixes:
https://github.com/SpiNNakerManchester/sPyNNaker7/issues/6
> Fix to allow spikesourceposisson to be initialized between multiple runs

- spynnaker/pyNN/utilities/utility_calls.py
fixed via checking if the parameter is a iterable. 
related to issue https://github.com/SpiNNakerManchester/sPyNNaker8/issues/13#issuecomment-306529777
> fixed issue with pynn 0-.8 and initise

- spynnaker/pyNN/models/recording_common.py
title
spy 8 depends on this (https://github.com/SpiNNakerManchester/sPyNNaker8/pull/21)
> fixes recording reset to reset instead of turning off recording

- spynnaker/pyNN/models/neuron/abstract_population_vertex.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_static.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
Especially is self does not have _model_name!
> when you say type use type(self). 

- neural_modelling/src/common/out_spikes.c
- neural_modelling/src/common/out_spikes.h
- neural_modelling/src/neuron/neuron.c
- neural_modelling/src/neuron/synapse_types/synapse_types_exponential_impl.h
- neural_modelling/src/neuron/synapses.c
- neural_modelling/src/spike_source/poisson/spike_source_poisson.c
- spynnaker/pyNN/models/common/eieio_spike_recorder.py
- spynnaker/pyNN/models/common/gsyn_inhibitory_recorder.py
Makes use of the recording DMA changes in SpiNNFrontEndCommon.
> Recording dma fix

- spynnaker/pyNN/models/neuron/synapse_io/synapse_io_row_based.py
Fix for https://github.com/SpiNNakerManchester/sPyNNaker8/issues/27
> type cast for strickter numpy13

- spynnaker/pyNN/abstract_spinnaker_common.py
Also requires pull in spynakker8
> moved run fix to correct place

- spynnaker/pyNN/models/pynn_population_common.py
- spynnaker/pyNN/models/recording_common.py
Depends on;
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/164
> check Is running

- spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/abstract_timing_dependence.py
- spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_spike_pair.py
- spynnaker/pyNN/models/neuron/plasticity/stdp/weight_dependence/abstract_weight_dependence.py
- spynnaker/pyNN/models/neuron/plasticity/stdp/weight_dependence/weight_dependence_additive.py
- spynnaker/pyNN/models/neuron/plasticity/stdp/weight_dependence/weight_dependence_multiplicative.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_static.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
- spynnaker/pyNN/models/pynn_projection_common.py
fixes issue with reset and remapping the graph when a new projection is put in. 
depends on spynnaker8 eqiv pull request 
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/35
> Fix projection remap

- .gitignore
- spynnaker/pyNN/models/neuron/connection_holder.py
- spynnaker/pyNN/models/pynn_projection_common.py
- unittests/model_tests/neuron/test_connection_holder.py
Allows the connection holder to work with extra PyNN 0.8 requirements
> Fix connection holder pynn 8

- spynnaker/pyNN/models/common/abstract_uint32_recorder.py
- should be 32768.0, not 32767.0
Fix of https://github.com/SpiNNakerManchester/sPyNNaker/issues/260
> Divide by correct value

- spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
> fixes for LPG over allocating LPGs

- spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
- as described in issue 216
Fix of https://github.com/SpiNNakerManchester/sPyNNaker/issues/216
> Fix _connection_slices to correct range

- spynnaker/pyNN/spynnaker.cfg
^
title     |
depends upon 
1.https://github.com/SpiNNakerManchester/sPyNNaker8/pull/42
2. https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/173
> supports having no vertices in graph via config file

- spynnaker/pyNN/connections/ethernet_control_connection.py
Wild tracebacks are a problem; let's crush them where possible!
> Tracebacks should be done through the logger as much as possible

- spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_pfister_spike_triplet.py
- spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_recurrent.py
- spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_spike_nearest_pair.py
- spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_vogels_2011.py
- spynnaker/pyNN/models/neuron/plasticity/stdp/weight_dependence/weight_dependence_additive_triplet.py
Updated after coming back from holiday and decided to try to run everything in PyNN7/8Examples to test it - discovered a few things that needed updating.
> Stdp extramodels fix

- spynnaker/pyNN/models/neuron/neuron_models/abstract_neuron_model.py
> Fix the read back of parameters when there are globals

- spynnaker/pyNN/models/neuron/synaptic_manager.py
- unittests/model_tests/neuron/test_synaptic_manager.py
Fixed an issue where the direct matrix was not being read back correctly.  A test has been added.
> Fix read direct matrix

- spynnaker/pyNN/abstract_spinnaker_common.py
> Add front end provenance

- spynnaker/pyNN/models/neural_projections/projection_machine_edge.py
> fixes a repr of an edge

- spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
- spynnaker/pyNN/utilities/random_stats/abstract_random_stats.py
- spynnaker/pyNN/utilities/utility_calls.py
All three pull request must be done at the same time!
> Use AbstractRandomStats for high and low vs boundaries refactor

- spynnaker/pyNN/utilities/random_stats/abstract_random_stats.py
Merging immediately as just docstrings!
> Update to match actual description

- spynnaker/pyNN/models/pynn_population_common.py
Merge this along with the pull requests in sPyNNaker7, sPyNNaker8 and PyNN8Examples (PyNN7Examples was already done)
> Move get_spike_counts common code to sPyNNaker

- spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
Found this when trying the run the microcircuit again...
> Fix boundaries

- neural_modelling/src/spike_source/poisson/spike_source_poisson.c
Fix of https://github.com/SpiNNakerManchester/sPyNNaker8/issues/81
> Write correct seed at start of (multi-)run

- .travis.yml
This adds building of the C code (neural models, etc.) to our Travis test script.
It also copies a few best practices over from SpiNNFrontEndCommon.
> C build in travis

- spynnaker/pyNN/models/recording_common.py
As there can be different sampling intervals, I will later get it from the data.
> removed shared sampling interval

- spynnaker/pyNN/models/pynn_population_common.py
fix for https://github.com/SpiNNakerManchester/sPyNNaker/issues/447
> fixed dict iteration

- spynnaker/pyNN/abstract_spinnaker_common.py
- spynnaker/pyNN/models/pynn_projection_common.py
allows to adapt to spalloc machines which come with different formats as the original one it was mapped to.
has a fec related one as well.
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/256
> fixes issues with machines and spalloc

- spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
fixes  https://github.com/SpiNNakerManchester/sPyNNaker8/issues/100
includes a spynnaker8 pr
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/101
> fixes property issue

- spynnaker/pyNN/models/neuron/synapse_io/synapse_io_row_based.py
Fix for https://github.com/SpiNNakerManchester/sPyNNaker/issues/457 (raised on user mailing list).
> Fix for get_weights when using STDP

- spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py
i_offset just needed making consistent with other properties
> Fix i_offset setter and set_neural_parameters()

- spynnaker/pyNN/models/abstract_models/abstract_accepts_incoming_synapses.py
- spynnaker/pyNN/models/neuron/abstract_population_vertex.py
- spynnaker/pyNN/models/neuron/synaptic_manager.py
- spynnaker/pyNN/models/pynn_projection_common.py
Fixes #476 
Must be merged with SpiNNakerManchester/SpiNNFrontEndCommon#290.
> Pass down fixed routes to get weights

- spynnaker/pyNN/utilities/ranged/spynakker_ranged_list.py
Part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/49
> handle set by lambda

- spynnaker/pyNN/models/common/neuron_recorder.py
you can not do range + range without first expanding the ranges so expand when on adding
> python3 fix

- neural_modelling/src/delay_extension/delay_extension.c
- neural_modelling/src/neuron/neuron.c
- neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
- neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c
- neural_modelling/src/neuron/population_table/population_table_fixed_impl.c
- neural_modelling/src/neuron/synapses.c
- neural_modelling/src/robot_motor_control/robot_motor_control.c
- neural_modelling/src/spike_source/poisson/spike_source_poisson.c
Companion to SpiNNakerManchester/SpiNNFrontEndCommon#326
> Remove #include that wasn't needed and caused failures

- spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
Support needed for SpiNNakerManchester/sPyNNaker8#152
> Add RNG support

- .travis.yml
- setup.py
NB: `csa` should be in `setup.py` as well as `requirements.txt`; this was making the `master` build of sPyNNaker7 fail
> Add required package

- setup.py
Simple fix so merging - just to let you know!
> Update to install dict files

- spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py
Carrying on from https://github.com/SpiNNakerManchester/sPyNNaker/pull/549
> cover cases where machine_time_step is < 1000

- neural_modelling/src/neuron/implementations/neuron_impl_semd.h
- neural_modelling/src/neuron/implementations/neuron_impl_standard.h
As prompted by https://github.com/SpiNNakerManchester/sPyNNaker/issues/554 - I'm not sure how these includes got in, but they aren't needed.
> Remove unneeded string.h

- spynnaker/pyNN/models/neuron/implementations/struct.py
Fix of https://github.com/SpiNNakerManchester/sPyNNaker/issues/556 - needed to take care of special case where a component has no parameters (e.g. InputTypeCurrent).
> Fix to make run-set-run work

- spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py
Value missing on update_data, causing Izhikevich models to fail when using run-set-run.
> Missing value to unpack

- neural_modelling/src/neuron/implementations/neuron_impl.h
- neural_modelling/src/neuron/implementations/neuron_impl_semd.h
- neural_modelling/src/neuron/implementations/neuron_impl_standard.h
- neural_modelling/src/neuron/neuron.c
- neural_modelling/src/neuron/neuron.h
- neural_modelling/src/neuron/synapses.c
C code wasn't compiling in debug mode after the recent updates, this fixes it so that it works; whether this is the best way of doing it is open for debate...
> Fix so that "make SPYNNAKER_DEBUG=DEBUG" actually works

- spynnaker/pyNN/connections/spynnaker_poisson_control_connection.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
Simple changes that allow the Poisson source to run forever
> Fixes to allow Poisson to run forever

- spynnaker/pyNN/models/neural_projections/projection_machine_edge.py
- spynnaker/pyNN/models/neuron/synaptic_manager.py
Fixing issue https://github.com/SpiNNakerManchester/sPyNNaker/issues/566 - @rowleya this affects the synapse expander a bit in that I think we have to remove the direct matrix option... ?
> Fix so that multiple connectors on the same edge behave correctly

- unittests/model_tests/neuron/test_synaptic_manager.py
Proof and TEMPORARY UGLY HACKY sticky plaster for for https://github.com/SpiNNakerManchester/sPyNNaker/issues/607
> UGLY HACK!

- .travis.yml
We need this anyway to get full ISO C11 support.
> Upgrade to Xenial (gcc 4.9, etc) and colorize the output of gcc

- spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
Fix for issue https://github.com/SpiNNakerManchester/sPyNNaker/issues/612.
> A four character fix.  Oops.

- setup.py
- spynnaker/pyNN/external_devices_models/external_device_lif_control_vertex.py
- spynnaker/pyNN/models/abstract_pynn_model.py
- spynnaker/pyNN/models/common/neuron_recorder.py
- spynnaker/pyNN/models/defaults.py
- spynnaker/pyNN/models/neuron/synaptic_manager.py
- spynnaker/pyNN/models/recording_common.py
- spynnaker/pyNN/models/utility_models/delay_extension_vertex.py
- spynnaker/pyNN/utilities/extracted_data.py
Part of https://github.com/SpiNNakerManchester/SpiNNUtils/issues/75
> Deprecation warning

- spynnaker/pyNN/models/pynn_population_common.py
fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/634
> fix auto labeling of populations

- spynnaker/pyNN/models/common/eieio_spike_recorder.py
- spynnaker/pyNN/models/common/multi_spike_recorder.py
- spynnaker/pyNN/models/common/neuron_recorder.py
Updates scripts to get data by placement and directly from BufferedReceivingData
Must be done at the same time as: SpiNNakerManchester/SpiNNFrontEndCommon#363
EDIT: must be at same time as SpiNNakerManchester/SpiNNFrontEndCommon#372
> Buffer cleanup

- spynnaker/pyNN/external_devices_models/munich_spinnaker_link_motor_device.py
- spynnaker/pyNN/models/neuron/abstract_population_vertex.py
- spynnaker/pyNN/models/neuron/synaptic_manager.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
- spynnaker/pyNN/models/utility_models/delay_extension_vertex.py
Matching PR for SpiNNakerManchester/SpiNNFrontEndCommon#429
> Fix sdram allocations

- spynnaker/pyNN/models/neuron/plasticity/stdp/common/plasticity_helpers.py
Ran new test when merging https://github.com/SpiNNakerManchester/sPyNNaker8/pull/215/ and it failed when using python 3, this fixes it.
> Fix report writing for python 3

- spynnaker/pyNN/abstract_spinnaker_common.py
part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/104
> get_existing_xys_on_board

- spynnaker/pyNN/models/neuron/synaptic_manager.py
> Make the index order of the synapse info match the block order

- spynnaker/pyNN/models/neuron/synaptic_manager.py
This still wasn't quite right - I had an example where it was failing, but this fixes it.  Can you check again with your own example and see that I haven't broken it again?
> Fix to the indexing of synapse info

- doc/source/conf.py
- setup.py
exclude csa from setup if in readthedocs as it depends on matplotlib
> Readthedocs

- neural_modelling/src/delay_extension/delay_extension.c
- neural_modelling/src/neuron/c_main.c
- neural_modelling/src/robot_motor_control/robot_motor_control.c
- neural_modelling/src/spike_source/poisson/spike_source_poisson.c
- spynnaker/pyNN/abstract_spinnaker_common.py
- spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/array_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/csa_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/index_based_probability_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/small_world_connector.py
- spynnaker/pyNN/models/neuron/abstract_population_vertex.py
- spynnaker/pyNN/models/neuron/implementations/ranged_dict_vertex_slice.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_static.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py
- spynnaker/pyNN/models/neuron/synaptic_manager.py
- spynnaker/pyNN/models/pynn_population_common.py
- spynnaker/pyNN/spynnaker_simulator_interface.py
- spynnaker/pyNN/utilities/spynnaker_failed_state.py
- unittests/mocks.py
- unittests/utilities_tests/test_spinnaker_main_interface.py
Changes associated with SpiNNakerManchester/SpiNNFrontEndCommon#450
> Better reset support

- spynnaker/pyNN/protocols/munich_io_ethernet_protocol.py
Fixes the pushbot wifi code for Python 3
> Python3 pushbot

- spynnaker/pyNN/abstract_spinnaker_common.py
- unittests/utilities_tests/test_spinnaker_main_interface.py
Part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/474
> sim setup with n_boards

- neural_modelling/src/spike_source/poisson/spike_source_poisson.c
- spynnaker/pyNN/connections/ethernet_control_connection.py
Fixes the output of control packets when behind a firewall. 
Also fixes the changing of the rate of Poisson sources to 0.
> Fix ethernet control connection

- spynnaker/pyNN/connections/spynnaker_poisson_control_connection.py
Stop the sPyNNaker Live Poisson Control code reaching inside the implementation of the Live Event Connection. All it needs to do now is ask the LEC core to send EIEIO packets to a particular labelled vertex, which is a much better division of responsibilities.
> Stop reaching into code where there are things that don't concern you!

- spynnaker/pyNN/abstract_spinnaker_common.py
- spynnaker/pyNN/models/pynn_population_common.py
- spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
- unittests/mocks.py
Please wait for SpiNNakerManchester/sPyNNaker8#250 to verify that there are no monsters under the bed.
Recommended to do at same time as:
SpiNNakerManchester/SpiNNFrontEndCommon#470
SpiNNakerManchester/SpiNNakerGraphFrontEnd#119
> Manage unigue labels in abstractSpynnaker base only

- setup.py
- spynnaker/pyNN/external_devices_models/external_device_lif_control_vertex.py
- spynnaker/pyNN/models/abstract_pynn_model.py
- spynnaker/pyNN/models/common/neuron_recorder.py
- spynnaker/pyNN/models/neuron/synaptic_manager.py
- spynnaker/pyNN/models/recording_common.py
- spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
- spynnaker/pyNN/utilities/extracted_data.py
https://github.com/SpiNNakerManchester/SpiNNUtils/issues/102
> fixed incorrect import from collections.abc

- spynnaker/pyNN/abstract_spinnaker_common.py
- spynnaker/pyNN/models/pynn_population_common.py
- spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
- unittests/mocks.py
Part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/501
to fix https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/499
> prefix never used so NUKE!

- spynnaker/pyNN/models/pynn_population_common.py
- spynnaker/pyNN/models/recording_common.py
minor cleanup before the spynnaker8 merge in
> Pynn7 cleanup

- neural_modelling/src/synapse_expander/connection_generators/connection_generator_all_to_all.h
- neural_modelling/src/synapse_expander/connection_generators/connection_generator_fixed_post.h
- neural_modelling/src/synapse_expander/connection_generators/connection_generator_fixed_prob.h
- neural_modelling/src/synapse_expander/connection_generators/connection_generator_one_to_one.h
- spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/small_world_connector.py
- spynnaker/pyNN/models/neuron/synaptic_manager.py
- spynnaker/pyNN/models/pynn_projection_common.py
- unittests/connector_tests/test_csa_connector.py
- unittests/model_tests/neuron/test_synaptic_manager.py
- unittests/model_tests/test_connectors.py
Reverts #718.
Some deduction has shown that this us causing some issues in master, so reverting until a fix is found...
Will create a PR to bring this back in a minute...
> Revert "Projections on popviews"

- spynnaker/pyNN/models/common/eieio_spike_recorder.py
Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/728
Test added to sPyNNaker8.
> Fix for when a core has an empty spike_times list

- spynnaker/pyNN/models/common/eieio_spike_recorder.py
Reverts SpiNNakerManchester/sPyNNaker#729 (broken integration tests)
> Revert "Fix for when a core has an empty spike_times list"

- spynnaker/pyNN/models/common/eieio_spike_recorder.py
Fixes #728 
Accompanying test in https://github.com/SpiNNakerManchester/sPyNNaker8/pull/303
Needs to be merged at same time as https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/511
> Fix for integration tests with unusual spike source input

- neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_vogels_2011_impl.c
> Fix vogels

- spynnaker/pyNN/connections/spynnaker_poisson_control_connection.py
Quick fix for https://github.com/SpiNNakerManchester/sPyNNaker/issues/732
> stop changing one label and using another.

- spynnaker/pyNN/models/common/neuron_recorder.py
- spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py
- spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
- spynnaker/pyNN/models/neuron/generator_data.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
- spynnaker/pyNN/models/utility_models/delays/delay_generator_data.py
- spynnaker/pyNN/utilities/utility_calls.py
It's complicated enough without spreading it all over the place. Let one class, `DataType`, be the sole expert on conversions.
See also SpiNNakerManchester/DataSpecification#77
> One conversion site

- spynnaker/pyNN/models/pynn_projection_common.py
Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/747
> Compare milliseconds to milliseconds, not ticks

- unittests/model_tests/neuron/test_neural_parameter.py
Fix for https://github.com/SpiNNakerManchester/sPyNNaker/issues/761
But Onloy if platform == "Windows"
> Reverted safer way to get around windows permsion denied problem

- spynnaker/pyNN/models/neuron/abstract_population_vertex.py
We should really be checking that variables can be initialized before trying to initialize them...
> Add a check that a variable can be initialized

- spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
- unittests/model_tests/test_connectors.py
Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/587
> Fix n_connections to post vertex for FixedNumberPostConnector

- neural_modelling/src/synapse_expander/connection_generators/connection_generator_all_to_all.h
- neural_modelling/src/synapse_expander/connection_generators/connection_generator_one_to_one.h
Fixes the generator to work when only some of the connections are generated.
Currently being tested by SpiNNakerManchester/sPyNNaker8#342
> Fix one to one generator

- spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_recurrent.py
This lets us write it in the DSG more compactly
> Generate the inverse CDF lut as a numpy array

- spynnaker/pyNN/models/neuron/structural_plasticity/synaptogenesis/elimination/random_by_weight_elimination.py
Fix spelling mistake noticed in https://github.com/SpiNNakerManchester/PyNN8Examples/pull/32
> fix incorrect spelling

- neural_modelling/makefiles/neuron/IF_curr_delta/Makefile
- neural_modelling/src/neuron/input_types/input_type_delta.h
- neural_modelling/src/neuron/synapse_types/synapse_types_delta_impl.h
- spynnaker/pyNN/models/neuron/builds/if_curr_delta.py
- spynnaker/pyNN/models/neuron/input_types/__init__.py
- spynnaker/pyNN/models/neuron/input_types/input_type_delta.py
Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/762
> Updates to IFCurrDelta, make it work for ts=0.1

- neural_modelling/src/neuron/neuron_recording.c
the instigator of all evil hath been vanquished
> fixed @rowleya pre optimisation.

- spynnaker/pyNN/models/utility_models/spike_injector/spike_injector_vertex.py
Building on SpiNNakerManchester/SpiNNFrontEndCommon#518, the SpikeInjector is always injecting, so tell the RIPTMCS this.
> Fix injection

- neural_modelling/src/synapse_expander/common_kernel.c
- neural_modelling/src/synapse_expander/common_kernel.h
Make KernelConnector work correctly for neuron index > UINT16_MAX
> Kernel uint32 fix

- spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
- spynnaker/pyNN/models/neuron/abstract_pynn_neuron_model.py
- spynnaker/pyNN/models/neuron/structural_plasticity/synaptogenesis/elimination/random_by_weight_elimination.py
- spynnaker/pyNN/models/neuron/structural_plasticity/synaptogenesis/formation/distance_dependent_formation.py
- spynnaker/pyNN/models/neuron/structural_plasticity/synaptogenesis/partner_selection/last_neuron_selection.py
- spynnaker/pyNN/models/neuron/structural_plasticity/synaptogenesis/partner_selection/random_selection.py
Must be done at or before merging https://github.com/SpiNNakerManchester/PACMAN/pull/281
> overrides is now ONLY in spinutils!

- unittests/model_tests/test_connectors.py
@rowleya we have been testing the same 1000 random number every time for 2 years now.
Lets just test ten each time from now on!
> 10 randon tries is enough after 2 years

- spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
Needed for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/554
> Use spinnutils Socket Address

- neural_modelling/makefiles/neuron/eprop_adaptive_stdp_mad_eprop_reg/Makefile
- neural_modelling/makefiles/neuron/neural_build.mk
- neural_modelling/src/neuron/implementations/neuron_impl_eprop_adaptive.h
- neural_modelling/src/neuron/models/neuron_model_eprop_adaptive_impl.c
- neural_modelling/src/neuron/plasticity/stdp/stdp_typedefs.h
- neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_eprop_adaptive_impl.c
- neural_modelling/src/neuron/plasticity/stdp/synapse_structure/synapse_structure.h
- neural_modelling/src/neuron/plasticity/stdp/synapse_structure/synapse_structure_weight_impl.h
- neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_eprop_impl.c
- neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_eprop_impl.h
- neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight.h
- neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_eprop_reg_impl.c
- neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_eprop_reg_impl.h
- neural_modelling/src/neuron/synapses.c
- spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/__init__.py
- spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_eprop.py
- spynnaker/pyNN/models/neuron/plasticity/stdp/weight_dependence/__init__.py
- spynnaker/pyNN/models/neuron/plasticity/stdp/weight_dependence/weight_dependence_eprop_reg.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
- spynnaker/pyNN/models/neuron/synaptic_manager.py
Proposed changes to add plastic weight changes to eprop code base
> Implement eprop plastic update

- spynnaker/pyNN/models/common/neuron_recorder.py
- unittests/model_tests/neuron/test_neuron_recorder.py
Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/802
As far as I can see this is no longer used.
> Nuke no longer required unused functions

- neural_modelling/src/bit_field_expander/bit_field_expander.c
> little clean up. needs fixing as algorithm not sorting now

- neural_modelling/src/neuron/models/neuron_model_eprop_adaptive_impl.c
- neural_modelling/src/neuron/models/neuron_model_eprop_adaptive_impl.h
- neural_modelling/src/neuron/models/neuron_model_sinusoid_readout_impl.c
- neural_modelling/src/neuron/models/neuron_model_sinusoid_readout_impl.h
- neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_eprop_adaptive_impl.c
- neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_sinusoid_readout_impl.c
- spynnaker/pyNN/models/neuron/neuron_models/neuron_model_eprop_adaptive.py
- spynnaker/pyNN/models/neuron/neuron_models/neuron_model_sinusoid_readout.py
Prototype method to delay weight updates over multiple iterations
> Add functionality to apply weight updates after an elapsed period of

- neural_modelling/makefiles/neuron/Makefile
- neural_modelling/makefiles/neuron/left_right_readout_stdp_mad_eprop_reg/Makefile
- neural_modelling/src/neuron/implementations/neuron_impl_eprop_adaptive.h
- neural_modelling/src/neuron/implementations/neuron_impl_left_right_readout.h
- neural_modelling/src/neuron/models/neuron_model_eprop_adaptive_impl.c
- neural_modelling/src/neuron/models/neuron_model_eprop_adaptive_impl.h
- neural_modelling/src/neuron/models/neuron_model_left_right_readout_impl.c
- neural_modelling/src/neuron/models/neuron_model_left_right_readout_impl.h
- neural_modelling/src/neuron/models/neuron_model_sinusoid_readout_impl.c
- neural_modelling/src/neuron/models/neuron_model_sinusoid_readout_impl.h
- neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_eprop_adaptive_impl.c
- neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_left_right_readout_impl.c
- neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_sinusoid_readout_impl.c
- neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_eprop_reg_impl.h
- spynnaker/pyNN/models/neuron/abstract_population_vertex.py
- spynnaker/pyNN/models/neuron/builds/__init__.py
- spynnaker/pyNN/models/neuron/builds/left_right_readout.py
- spynnaker/pyNN/models/neuron/implementations/neuron_impl_standard.py
- spynnaker/pyNN/models/neuron/neuron_models/__init__.py
- spynnaker/pyNN/models/neuron/neuron_models/neuron_model_eprop_adaptive.py
- spynnaker/pyNN/models/neuron/neuron_models/neuron_model_left_right_readout.py
- spynnaker/pyNN/models/neuron/neuron_models/neuron_model_sinusoid_readout.py
Mainly adding of a new task, changes to regularisation and weight updates
> Eprop left right

- neural_modelling/src/neuron/neuron.h
- neural_modelling/src/neuron/plasticity/stdp/maths.h
- neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h
Add includes in places that really should have had them before now.
> Recent merge showed up some places that were missing includes

- spynnaker/pyNN/models/abstract_models/abstract_accepts_incoming_synapses.py
- spynnaker/pyNN/models/neuron/abstract_population_vertex.py
- spynnaker/pyNN/models/neuron/synaptic_manager.py
- spynnaker/pyNN/models/pynn_projection_common.py
this moves te setting of the system routes and the timeouts from a machine vertex level to the projection level. MASSIVELY speeds up matrix extraction
JENKINS: https://github.com/SpiNNakerManchester/sPyNNaker8/pull/419
> changes to speed up matrix extraction massively.

- spynnaker/pyNN/overridden_pacman_functions/algorithms_metadata.xml
- spynnaker/pyNN/overridden_pacman_functions/on_chip_bit_field_generator.py
- spynnaker/pyNN/overridden_pacman_functions/spynnaker_machine_bit_field_router_compressor.py
as asked by #635
would like this accepted and merged before i revisit the other tweaks
> tweeky tweeky

- spynnaker/pyNN/abstract_spinnaker_common.py
- spynnaker/pyNN/overridden_pacman_functions/algorithms_metadata.xml
- spynnaker/pyNN/overridden_pacman_functions/spynnaker_machine_bit_field_router_compressor.py
- spynnaker/pyNN/spynnaker.cfg
title
syn 8 link
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/423
> bool flag for turning off iobuf for rerun expander

- spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
this makes views which would have originally been files. With just the all view, its a pain to find what your looking for. this at least reduces the scope of things to be more manageable. Aka, when looking for max size the input buffer got to. 
depends on a FEC change as well:
https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/641
> more views of the prov db to make it easier to use

- .ratexcludes
- .travis.yml
- neural_modelling/.common_template.tag
- neural_modelling/.fec_template.tag
- neural_modelling/.gitignore
- neural_modelling/.sllt_template.tag
- neural_modelling/Doxyfile
- neural_modelling/Makefile
Final part of documentation cross-linking
See also:
* SpiNNakerManchester/spinnaker_tools#131
* SpiNNakerManchester/spinn_common#42
* SpiNNakerManchester/SpiNNFrontEndCommon#643
> Cross link to dependencies (and generate a spynnaker.tag file)

- .travis.yml
- setup.py
- spynnaker/pyNN/extra_algorithms/redundant_packet_count_report.py
- spynnaker/pyNN/extra_algorithms/synapse_expander.py
Version of Linux in use locked because of C compiler requirements
> Add testing with Python 3.8

- spynnaker/pyNN/external_devices_models/__init__.py
- spynnaker/pyNN/external_devices_models/machine_munich_motor_device.py
- spynnaker/pyNN/external_devices_models/munich_spinnaker_link_motor_device.py
- spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
- spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
- spynnaker/pyNN/models/neuron/abstract_population_vertex.py
- spynnaker/pyNN/models/neuron/population_machine_vertex.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
- spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
- spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
Required for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/649  (could be done before)
> Binary from machine

- spynnaker/pyNN/extra_algorithms/on_chip_bit_field_generator.py
this im sure is fixed elsewhere. but given it still exists in maste,r maybe that fix got lost somewhere?
> fix of reading bitfields back. seems to have got lost somewhere

- spynnaker/pyNN/models/pynn_population_common.py
title
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/437
> fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/865

- spynnaker/pyNN/models/neuron/master_pop_table.py
- spynnaker/pyNN/models/neuron/synaptic_matrix.py
- spynnaker/pyNN/models/neuron/synaptic_matrix_app.py
*** This is a PR on pop_based_master_pop_table, not master ***
This is the master pop table adding split in 2 for you to examine and decide if you like it.
> Changes requested by Alan, done here first in case he doesn't like it

- neural_modelling/src/delay_extension/delay_extension.c
- neural_modelling/src/delay_extension/delay_extension.h
- spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/850
> kfixes the key issue for filtered delays

- unittests/model_tests/neuron/test_get_max_synapses.py
Tested by SpiNNakerManchester/sPyNNaker8#447
> Remove timeout from test

- .travis.yml
- doc/doc_requirements.txt
- doc/source/conf.py
- pypi_to_import
- requirements.txt
- setup.py
- unittests/model_tests/neuron/test_neural_parameter.py
- unittests/model_tests/neuron/test_synaptic_manager.py
- unittests/test_version.py
Purging the use of SpiNNStorageHandlers; the value of that repo is now zero.
See https://github.com/SpiNNakerManchester/SpiNNMan/pull/221
> No more storage handlers

- spynnaker/pyNN/models/neuron/synaptic_matrix_app.py
Adds support for the case that was failing in SpiNNakerManchester/sPyNNaker8#479 (which also tests this case).
> Add missing support

- spynnaker/pyNN/models/pynn_population_common.py
- unittests/test_populations/test_population.py
Fix for https://github.com/SpiNNakerManchester/sPyNNaker/issues/909
> fixed and test round warning

- spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_slice.py
- spynnaker/pyNN/extra_algorithms/splitter_components/splitter_delay_vertex_slice.py
- spynnaker/pyNN/extra_algorithms/splitter_components/spynnaker_splitter_slice_legacy.py
part of https://github.com/SpiNNakerManchester/PACMAN/pull/317
> refactored get vertices methods so they are the same name as slice ones

- spynnaker/pyNN/external_devices_models/machine_munich_motor_device.py
- spynnaker/pyNN/external_devices_models/munich_spinnaker_link_motor_device.py
Depends on https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/685
> MunichMotorDevice most functionaility moved to machine level

- .github/workflows/python_actions.yml
- .ratexcludes
- spynnaker/pyNN/external_devices_models/external_spinnaker_link_fpga_retina_device.py
- spynnaker/pyNN/external_devices_models/push_bot/abstract_push_bot_retina_device.py
- spynnaker/pyNN/models/abstract_models/__init__.py
- spynnaker/pyNN/models/abstract_models/abstract_accepts_incoming_synapses.py
- spynnaker/pyNN/models/abstract_models/abstract_has_delay_stages.py
- spynnaker/pyNN/models/abstract_models/abstract_synapse_expandable.py
- spynnaker/pyNN/models/common/neuron_recorder.py
- spynnaker/pyNN/models/neural_projections/projection_application_edge.py
- spynnaker/pyNN/models/neuron/master_pop_table.py
- spynnaker/pyNN/models/neuron/population_machine_vertex.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics_structural.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
- spynnaker/pyNN/models/neuron/synapse_io.py
- spynnaker/pyNN/models/neuron/synaptic_manager.py
- spynnaker/pyNN/models/neuron/synaptic_matrices.py
- spynnaker/pyNN/models/neuron/synaptic_matrix.py
- spynnaker/pyNN/models/neuron/synaptic_matrix_app.py
- spynnaker/pyNN/models/pynn_population_common.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
- spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
- spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
- spynnaker/pyNN/utilities/bit_field_utilities.py
Includes https://github.com/SpiNNakerManchester/sPyNNaker/pull/918
> Turn on github actions Python side

- spynnaker/pyNN/extra_algorithms/delay_support_adder.py
> DelaySupportAdder cleanup

- .github/workflows/python_actions.yml
- requirements-test.txt
Builds on https://github.com/SpiNNakerManchester/sPyNNaker/pull/920
> Turn on shpinx in python actions

- .github/workflows/c_actions.yml
> Add C actions

- .github/workflows/publish.yml
Keep our documentation up to date with this one handy trick!
> Define a publish action

- spynnaker/pyNN/extra_algorithms/on_chip_bit_field_generator.py
- spynnaker/pyNN/extra_algorithms/spynnaker_machine_bit_field_router_compressor.py
- spynnaker/pyNN/extra_algorithms/spynnaker_neuron_network_specification_report.py
Tricky point: we were not previously correct about how we were doing the read-back in some cases. That's now all shared code so there's a better chance that we'll do the critical bits (that read structures off the machine) correctly.
> Improved version of bitfield generation and reporting

- spynnaker/pyNN/external_devices_models/push_bot/push_bot_spinnaker_link/push_bot_spinnaker_link_laser_device.py
- spynnaker/pyNN/external_devices_models/push_bot/push_bot_spinnaker_link/push_bot_spinnaker_link_led_device.py
- spynnaker/pyNN/external_devices_models/push_bot/push_bot_spinnaker_link/push_bot_spinnaker_link_motor_device.py
- spynnaker/pyNN/external_devices_models/push_bot/push_bot_spinnaker_link/push_bot_spinnaker_link_speaker_device.py
this is whats actually acceptable to these.
> doc changes

- neural_modelling/src/neuron/models/neuron_model_eprop_adaptive_impl.h
- neural_modelling/src/neuron/synapse_row.h
- neural_modelling/src/neuron/synapses.c
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_static.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
- spynnaker/pyNN/models/neuron/synapse_io/synapse_io_row_based.py
> Add capability for 10-bit delays (and hence synapse indexing)

- doc/source/conf.py
- requirements.txt
- setup.py
https://github.com/SpiNNakerManchester/PACMAN/pull/337
> Version binding for numpy

- requirements.txt
- setup.py
https://github.com/SpiNNakerManchester/SpiNNUtils/pull/126
> Corrections to numpy version requirements

- requirements.txt
Part fix for https://github.com/SpiNNakerManchester/sPyNNaker/issues/956
Also requires https://github.com/SpiNNakerManchester/sPyNNaker8/pull/521
> upgrade neo

- spynnaker/pyNN/models/spike_source/spike_source_array_vertex.py
Fixes https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/529
An integration test can probably be written to check this works if desired?
> Warn if user supplies spike time for SSA that's too low

- spynnaker/pyNN/models/neuron/additional_inputs/additional_input_ca2_adaptive.py
- spynnaker/pyNN/models/neuron/builds/if_cond_exp_base.py
- spynnaker/pyNN/models/neuron/builds/if_cond_exp_stoc.py
- spynnaker/pyNN/models/neuron/builds/if_curr_alpha.py
- spynnaker/pyNN/models/neuron/builds/if_curr_delta.py
- spynnaker/pyNN/models/neuron/builds/if_curr_dual_exp_base.py
- spynnaker/pyNN/models/neuron/builds/if_curr_exp_base.py
- spynnaker/pyNN/models/neuron/builds/if_curr_exp_ca2_adaptive.py
- spynnaker/pyNN/models/neuron/builds/if_curr_exp_semd_base.py
- spynnaker/pyNN/models/neuron/builds/izk_cond_exp_base.py
- spynnaker/pyNN/models/neuron/builds/izk_curr_exp_base.py
- spynnaker/pyNN/models/neuron/implementations/abstract_standard_neuron_component.py
- spynnaker/pyNN/models/neuron/implementations/neuron_impl_standard.py
- spynnaker/pyNN/models/neuron/input_types/input_type_conductance.py
- spynnaker/pyNN/models/neuron/input_types/input_type_current_semd.py
- spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py
- spynnaker/pyNN/models/neuron/neuron_models/neuron_model_leaky_integrate_and_fire.py
- spynnaker/pyNN/models/neuron/synapse_types/synapse_type_alpha.py
- spynnaker/pyNN/models/neuron/synapse_types/synapse_type_delta.py
- spynnaker/pyNN/models/neuron/synapse_types/synapse_type_dual_exponential.py
- spynnaker/pyNN/models/neuron/synapse_types/synapse_type_exponential.py
- spynnaker/pyNN/models/neuron/synapse_types/synapse_type_semd.py
- spynnaker/pyNN/models/neuron/threshold_types/threshold_type_maass_stochastic.py
- spynnaker/pyNN/models/neuron/threshold_types/threshold_type_static.py
fixes models to be unmutable and fixes docs accordingly
> unmutable models

- spynnaker/pyNN/models/neuron/population_machine_vertex.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
Must be done be before or with https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/716
> remove AbstractRecordable as it was never used correctly

- p8_integration_tests/quick_test/test_onchip_compressor/test_host_bit_field/spynnaker.cfg
- p8_integration_tests/quick_test/test_onchip_compressor/test_host_bit_field/test_host_bit_field_compressor.py
- p8_integration_tests/quick_test/test_onchip_compressor/test_ordered_covering/spynnaker.cfg
- p8_integration_tests/quick_test/test_onchip_compressor/test_ordered_covering/test_ordered_covering_compressor.py
- p8_integration_tests/quick_test/test_onchip_compressor/test_ordered_covering_bit_field/spynnaker.cfg
- p8_integration_tests/quick_test/test_onchip_compressor/test_ordered_covering_bit_field/test_ordered_covering_bit_field_compressor.py
- p8_integration_tests/quick_test/test_onchip_compressor/test_unordered/spynnaker.cfg
- p8_integration_tests/quick_test/test_onchip_compressor/test_unordered_bit_field/spynnaker.cfg
- spynnaker/pyNN/extra_algorithms/algorithms_metadata.xml
- spynnaker/pyNN/extra_algorithms/spynnaker_machine_bit_field_router_compressor.py
- spynnaker/pyNN/spynnaker.cfg
test for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/726
replaces  https://github.com/SpiNNakerManchester/sPyNNaker8/pull/518
see https://github.com/SpiNNakerManchester/IntegrationTests/tree/host_bitfield_compressor for test results
> Host bitfield compressor cleanup (tests)

- .github/workflows/c_actions.yml
- .github/workflows/publish.yml
- .github/workflows/python_actions.yml
- doc/source/conf.py
- setup.py
python_actions changed to be more like other repositories
> added 3.9 and rat 3.8 (more like other repr)

- p8_integration_tests/base_test_case.py
- p8_integration_tests/quick_test/test_iobuf/test_iobuf_without_during_run_flag/test_noIobuf_during_run.py
- p8_integration_tests/quick_test/test_iobuf/test_multirun/test_multirun_with.py
- p8_integration_tests/quick_test/test_iobuf/test_none_but_active_recorded/test_no_cores.py
- spynnaker/pyNN/utilities/spynnaker_failed_state.py
Depends on https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/762
Read configs preview before sim.setup
Make use of the extra info available through global variables.
> More exposed via global variables

- spynnaker_integration_tests/test_various/test_from_file_connector_large.py
Recovers the lost 
https://github.com/SpiNNakerManchester/sPyNNaker8/tree/master/p8_integration_tests/test_from_file_connector
Which @andrewgait correctly points out was our only FromFile test
Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/975
tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/35
> recover and fix FromFile test

- spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics_structural.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_stdp.py
Small doc fixes of synapse dynamics
fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/833
fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/835
> Small doc fixes

- requirements-test.txt
Part of https://github.com/SpiNNakerManchester/TestBase/pull/6 which must be done first
> Spinnaker testbase

- README.md
> remove double newline

- spynnaker/pyNN/abstract_spinnaker_common.py
- spynnaker/pyNN/models/neuron/abstract_population_vertex.py
- spynnaker/pyNN/models/neuron/synaptic_manager.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
- spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
- spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
- spynnaker/pyNN/utilities/spynnaker_failed_state.py
- spynnaker_integration_tests/test_big_connection/test_big_connection.py
- spynnaker_integration_tests/test_debug_mode/check_debug.py
- spynnaker_integration_tests/test_many_boards/many_boards.py
- unittests/model_tests/neuron/test_synaptic_manager.py
- unittests/utilities_tests/test_spinnaker_main_interface.py
Part of https://github.com/SpiNNakerManchester/PACMAN/pull/371
> Making the configs truly global 

- spynnaker_integration_tests/test_debug_mode/check_debug.py
- unittests/test_using_virtual_board/test_debug_mode/test_debug.py
Part of https://github.com/SpiNNakerManchester/PACMAN/pull/382
> Move the reports to FEC

- .github/workflows/python_actions.yml
- requirements-test.txt
- setup.py
- spynnaker/pyNN/abstract_spinnaker_common.py
- spynnaker/pyNN/extra_algorithms/spynnaker_neuron_network_specification_report.py
- unittests/test_integration_using_virtual_board/spynnaker.cfg
This fixes #1078 (or will do once the PR is finished)
> Test with graphviz installed

- spynnaker/pyNN/models/spike_source/spike_source_array_vertex.py
fixed the sign in the comparison of spiketime to current time
after all 100 is not less than 0
> fixed the check for early spikes

- neural_modelling/Doxyfile
- neural_modelling/src/bit_field_expander/bit_field_expander.c
- neural_modelling/src/delay_extension/delay_extension.c
- neural_modelling/src/neuron/c_main_synapses.c
- neural_modelling/src/neuron/implementations/neuron_impl.h
- neural_modelling/src/neuron/implementations/neuron_impl_external_devices.h
- neural_modelling/src/neuron/implementations/neuron_impl_standard.h
- neural_modelling/src/neuron/models/neuron_model_izh_impl.h
- neural_modelling/src/neuron/models/neuron_model_lif_impl.h
- neural_modelling/src/neuron/neuron.c
- neural_modelling/src/neuron/population_table/population_table.h
- neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c
- neural_modelling/src/neuron/spike_processing.c
- neural_modelling/src/neuron/spike_processing.h
- neural_modelling/src/neuron/spike_processing_fast.h
- neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h
- neural_modelling/src/neuron/structural_plasticity/synaptogenesis/topographic_map_impl.c
- neural_modelling/src/neuron/structural_plasticity/synaptogenesis_dynamics.h
- neural_modelling/src/neuron/synapse_row.h
- neural_modelling/src/neuron/synapse_types/synapse_types.h
- neural_modelling/src/neuron/synapse_types/synapse_types_alpha_impl.h
- neural_modelling/src/neuron/synapse_types/synapse_types_delta_impl.h
- neural_modelling/src/neuron/synapse_types/synapse_types_dual_excitatory_exponential_impl.h
- neural_modelling/src/neuron/synapse_types/synapse_types_exponential_impl.h
- neural_modelling/src/neuron/synapse_types/synapse_types_semd_impl.h
- neural_modelling/src/neuron/synapses.c
- neural_modelling/src/neuron/synapses.h
- neural_modelling/src/synapse_expander/delay_expander.c
Fix a whole bunch of minor warnings in the documentation build. There's apparently also a crash, but I can't reproduce that locally so I don't know if this fixes that.
> Documentation fix

- setup.py
There appears to be a dependency issue; this appears to fix it.
> Fix dependency issue

- spynnaker/pyNN/models/recorder.py
fixes: https://github.com/SpiNNakerManchester/sPyNNaker/issues/1123
Stand alone bug fix
> append the empty segment to the block

- spynnaker/pyNN/external_devices_models/push_bot/spinnaker_link/push_bot_retina_device.py
Part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/882
> Stop using @inject

- requirements.txt
- spynnaker_integration_tests/test_various/test_get_machine.py
Test for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/906
> Get machine2

- spynnaker_integration_tests/test_external_devices/test_live_neuron_voltage.py
Don't assume ordering in the live voltage test
> Fix Live Voltage Test

- spynnaker_integration_tests/test_stdp/test_STDP_record_weights.py
Adding a test using runtime callbacks as requested.
Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/89
> Add a weight recorder test using runtime callbacks

- spynnaker/pyNN/abstract_spinnaker_common.py
- spynnaker_integration_tests/test_onchip_compressor/many_bitfields.py
- spynnaker_integration_tests/test_onchip_compressor/many_routes.py
- spynnaker_integration_tests/test_onchip_compressor/one_route.py
- spynnaker_integration_tests/test_onchip_compressor/test_ordered_covering/spynnaker.cfg
- spynnaker_integration_tests/test_onchip_compressor/test_ordered_covering_bit_field/spynnaker.cfg
- spynnaker_integration_tests/test_onchip_compressor/test_pair/spynnaker.cfg
- spynnaker_integration_tests/test_onchip_compressor/test_pair_no_ranged/__init__.py
- spynnaker_integration_tests/test_onchip_compressor/test_pair_no_ranged/spynnaker.cfg
- spynnaker_integration_tests/test_onchip_compressor/test_pair_no_ranged/test_pair_no_ranged_compressor.py
Part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/914
> range compress

- spynnaker/pyNN/abstract_spinnaker_common.py
- spynnaker/pyNN/extra_algorithms/spynnaker_data_specification_writer.py
- spynnaker_integration_tests/test_debug_mode/check_debug.py
Part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/922
> Use the Data Spec database more

- requirements-test.txt
- requirements.txt
tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/110
> statistics no longer required

- doc/doc_requirements.txt
- requirements.txt
- setup.py
tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/109
> remove Lxml requirement

- setup.py
- spynnaker_integration_tests/scripts/synfire_runner.py
- spynnaker_integration_tests/test_external_devices/test_live_sync.py
- spynnaker_integration_tests/test_various/test_synaptic_expander.py
- unittests/test_cfg_checker.py
tested by 
http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/less8/1/pipeline
> remove spynnaker8 references

- neural_modelling/src/neuron/current_sources/current_source.h
- neural_modelling/src/neuron/current_sources/current_source_step.h
- spynnaker/pyNN/models/neuron/abstract_population_vertex.py
- spynnaker/pyNN/models/neuron/population_machine_neurons.py
- spynnaker_integration_tests/test_current_sources/__init__.py
- spynnaker_integration_tests/test_current_sources/test_single_step_current_source.py
Fix a bug in current sources which meant that certain examples didn't work (particularly with multiple neurons connected to the same current source).
Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/121
> Current source fix

- spynnaker/pyNN/spinnaker.py
- spynnaker_integration_tests/test_iobuf/test_cores_and_binaries_recorded/test_cores_and_binaries_recording.py
- spynnaker_integration_tests/test_iobuf/test_multirun/test_multirun_with.py
- spynnaker_integration_tests/test_iobuf/test_only_binaries_recorded/test_only_binaries_recording.py
Part of https://github.com/SpiNNakerManchester/PACMAN/pull/453
> hide Placements

- spynnaker_integration_tests/test_local_only/test_overlapping_network.py
Adds a test for SpiNNakerManchester/PACMAN#470
> Fix routing

- spynnaker_integration_tests/test_debug_mode/check_debug.py
- spynnaker_integration_tests/test_debug_mode/test_java_debug/test_debug.py
- spynnaker_integration_tests/test_debug_mode/test_python_debug/test_debug.py
Tests https://github.com/SpiNNakerManchester/SpiNNUtils/pull/198
I recommend these go in permanently
Can be merged after but not before.
> tests fix report_dir errors

- neural_modelling/src/synapse_expander/matrix_generators/matrix_generator_static.h
Remove print as overloading iobuf on very big runs
> Remove print

- .github/workflows/python_actions.yml
- spynnaker/pyNN/__init__.py
- spynnaker/pyNN/external_devices/__init__.py
- spynnaker/pyNN/extra_algorithms/splitter_components/spynnaker_splitter_fixed_legacy.py
- spynnaker/pyNN/models/common/neuron_recorder.py
- spynnaker/pyNN/models/neuron/neuron_data.py
Changes a pylint warning to a github action fail
Removes one unused param
disable pylint where we do it weird to hide stuff from user scripts.
Tested https://github.com/SpiNNakerManchester/IntegrationTests/pull/98
Independent of similar prs.
> Pylint fix

- spynnaker/gsyn_tools.py
- spynnaker/plot_utils.py
- spynnaker/pyNN/connections/ethernet_command_connection.py
- spynnaker/pyNN/external_devices/__init__.py
- spynnaker/pyNN/external_devices_models/push_bot/parameters/push_bot_retina_viewer.py
- spynnaker/pyNN/models/common/neuron_recorder.py
- spynnaker/pyNN/models/common/param_generator_data.py
- spynnaker/pyNN/models/defaults.py
- spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
- spynnaker/pyNN/models/neuron/connection_holder.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_common.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py
- spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_stdp.py
- spynnaker/pyNN/models/neuron/synaptic_matrix_app.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
- spynnaker/pyNN/setup_pynn.py
- spynnaker/pyNN/utilities/neo_buffer_database.py
- spynnaker/pyNN/utilities/utility_calls.py
- spynnaker/spike_checker.py
- spynnaker/spynnaker_plotting.py
- spynnaker8/__init__.py
- spynnaker_integration_tests/scripts/synfire_runner.py
- spynnaker_integration_tests/test_external_devices/test_live_neuron_voltage.py
- spynnaker_integration_tests/test_local_only/test_network_fake_retina_input.py
- spynnaker_integration_tests/test_selective_recording/test_sampling_by_compare.py
- test_whole_board/test_whole_board.py
- unittests/data/manual_check.py
- unittests/test_using_virtual_board/test_multiple_stdp_mechs_on_same_neuron.py
Fix raise Exception
ignore nest min max as pylint did not see the next on is over a list
> Pylint2.16.5

- unittests/connector_tests/test_csa_connector.py
A test was being skipped because of a downstream bug which is now fixed, so this removes the skip.
Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/181
> Update CSA block test

- neural_modelling/src/neuron/local_only/local_only_pool_dense_impl.c
- spynnaker/pyNN/models/neural_projections/connectors/pool_dense_connector.py
- spynnaker_integration_tests/test_local_only/test_pool_dense_odd.py
Fixing another oddity in this connector, along with a test
> Fix pool dense odd

- .github/dependabot.yml
- .github/workflows/c_actions.yml
- .github/workflows/publish.yml
- .github/workflows/python_actions.yml
* Add explicit timeouts to github jobs
* Add a dependabot config to keep action versions fresh
> Improve github integration

- spynnaker/pyNN/external_devices_models/machine_munich_motor_device.py
- spynnaker/pyNN/extra_algorithms/neuron_expander.py
- spynnaker/pyNN/extra_algorithms/spynnaker_machine_bit_field_router_compressor.py
- spynnaker/pyNN/extra_algorithms/synapse_expander.py
- spynnaker/pyNN/models/neuron/population_machine_common.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
- spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
Possible after https://github.com/SpiNNakerManchester/SpiNNMan/pull/323
> from spinnman.model.enums import ExecutableType

- .github/workflows/publish.yml
- README.md
- doc/global/index.html
- doc/global/python/index.html
- doc/source/conf.py
- neural_modelling/Doxyfile
- spynnaker/pyNN/external_devices_models/machine_munich_motor_device.py
- spynnaker/pyNN/extra_algorithms/neuron_expander.py
- spynnaker/pyNN/extra_algorithms/spynnaker_machine_bit_field_router_compressor.py
- spynnaker/pyNN/extra_algorithms/synapse_expander.py
- spynnaker/pyNN/models/neuron/population_machine_common.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
- spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
Same as https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1052
> Do no tpublish Python docs to github.io

- spynnaker/pyNN/external_devices_models/external_device_lif_control_vertex.py
- spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_fixed.py
- spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_neurons_synapses.py
- spynnaker/pyNN/extra_algorithms/splitter_components/splitter_delay_vertex_slice.py
- spynnaker/pyNN/extra_algorithms/splitter_components/splitter_poisson_delegate.py
- spynnaker/pyNN/models/neuron/abstract_population_vertex.py
- spynnaker/pyNN/models/neuron/abstract_pynn_neuron_model.py
- spynnaker/pyNN/models/spike_source/spike_source_array.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_variable.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
- spynnaker/pyNN/models/utility_models/spike_injector/spike_injector.py
See:
* https://github.com/SpiNNakerManchester/PACMAN/pull/511
> Clean up of splitter code

- spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
- spynnaker_integration_tests/test_connectors/test_kernel_connector.py
Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/1323
> Allow lists to be sent into kernel connector, update test

- spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
- spynnaker_integration_tests/test_multi_call_examples/poisson_reset.py
Ensure Poisson regenerates data correctly on new DSG, and test
> Fix poisson reset and dsg

- spynnaker/pyNN/models/neuron/synaptic_matrices.py
- spynnaker/pyNN/models/neuron/synaptic_matrix_app.py
Of course I mean without set_write_pointer!
Tested by SpiNNakerManchester/IntegrationTests#202
> Write synaptic matrices without set_write_pointer

- neural_modelling/makefiles/neuron/IZK_cond_exp_dual/Makefile
- neural_modelling/makefiles/neuron/IZK_cond_exp_dual_stdp_mad_pair_additive/Makefile
- neural_modelling/makefiles/neuron/Makefile
- neural_modelling/makefiles/neuron_only/IZK_cond_exp_dual_neuron/Makefile
- spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_neurons_synapses.py
- spynnaker/pyNN/extra_models/__init__.py
- spynnaker/pyNN/models/neuron/builds/__init__.py
- spynnaker/pyNN/models/neuron/builds/izk_cond_dual_exp_base.py
Build Izhikevich dual-excitatory synapse neuron models by default.
Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/208
> Izk cond exp dual

- unittests/model_tests/neuron/test_neural_parameter.py
- unittests/model_tests/neuron/test_synaptic_manager.py
part of https://github.com/SpiNNakerManchester/DataSpecification/pull/148
tested adapted
> Ds cleanup

- .github/workflows/c_actions.yml
needed to get around ITCM overflow
> runs-on: ubuntu-latest

- unittests/model_tests/neuron/test_synaptic_manager.py
part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1077
> Rename to load

- unittests/model_tests/neuron/test_synaptic_manager.py
needed due to https://github.com/SpiNNakerManchester/SpiNNMan/pull/336
> updated test as CPUInfo changed

- neural_modelling/Doxyfile
- setup.cfg
- spynnaker/_version.py
- spynnaker/pyNN/_version.py
part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/236
> Version bump

- spynnaker/pyNN/extra_algorithms/spynnaker_neuron_network_specification_report.py
- spynnaker/pyNN/spinnaker.py
part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/244
> Is config none

- neural_modelling/makefiles/neuron/IF_curr_delta_stdp_mad_nearest_pair_additive/Makefile
- neural_modelling/makefiles/neuron/IF_curr_delta_stdp_mad_pair_additive/Makefile
- neural_modelling/makefiles/neuron/Makefile
Build IF curr delta STDP models (being used in current work by @sergiodavies).
> If curr delta STDP

- spynnaker_integration_tests/test_stdp/test_IF_curr_delta_stdp.py
Add new integration tests using new binaries introduced in #1383 
Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/235
> Add tests for new IF_curr_delta STDP binaries

- spynnaker/pyNN/extra_algorithms/redundant_packet_count_report.py
- spynnaker/pyNN/utilities/neo_buffer_database.py
- unittests/model_tests/neuron/test_synaptic_manager.py
part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1112
> Use less transactions

- spynnaker/pyNN/connections/ethernet_control_connection.py
part of  https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1116
> use add_receive_no_time_callback

- unittests/model_tests/neuron/test_synaptic_manager.py
Part of https://github.com/SpiNNakerManchester/SpiNNMan/pull/366
replaces https://github.com/SpiNNakerManchester/sPyNNaker/pull/1379
> Hide CPUInfo object

- unittests/model_tests/neuron/test_synaptic_manager.py
https://github.com/SpiNNakerManchester/SpiNNMan/pull/376
Adjust to API change
> Changes for SpiNNMan Typing 

- spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_fixed.py
- spynnaker/pyNN/extra_algorithms/splitter_components/splitter_poisson_delegate.py
- spynnaker/pyNN/extra_algorithms/splitter_components/spynnaker_splitter_selector.py
- spynnaker/pyNN/models/abstract_models/receives_synaptic_inputs_over_sdram.py
- spynnaker/pyNN/models/abstract_models/sends_synaptic_inputs_over_sdram.py
- spynnaker/pyNN/models/common/population_application_vertex.py
- spynnaker/pyNN/models/neuron/population_machine_common.py
- spynnaker/pyNN/models/neuron/population_machine_neurons.py
- spynnaker/pyNN/models/neuron/population_machine_synapses.py
- spynnaker/pyNN/models/neuron/population_machine_synapses_provenance.py
- spynnaker/pyNN/models/neuron/population_machine_vertex.py
- spynnaker/pyNN/models/neuron/population_neurons_machine_vertex.py
- spynnaker/pyNN/models/spike_source/spike_source_array_machine_vertex.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
- spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
- unittests/model_tests/neuron/test_synaptic_manager.py
Minor changes to enable  https://github.com/SpiNNakerManchester/PACMAN/pull/529
> Pacman Typing information and some changes to make that easierRoc part

- setup.cfg
fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/1431
> remove spynnaker8 refrence

- spynnaker_integration_tests/test_onchip_compressor/many_bitfields.py
- spynnaker_integration_tests/test_onchip_compressor/many_routes.py
- spynnaker_integration_tests/test_onchip_compressor/one_route.py
- test_whole_board/test_whole_board.py
part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/246
overrides https://github.com/SpiNNakerManchester/sPyNNaker/pull/1438
> Chip simplification

- spynnaker_integration_tests/test_iobuf/test_cores_and_binaries_recorded/test_cores_and_binaries_recording.py
- spynnaker_integration_tests/test_iobuf/test_only_binaries_recorded/test_only_binaries_recording.py
part of https://github.com/SpiNNakerManchester/PACMAN/pull/552
> use xy tuple (which now includes Chip)

- unittests/test_integration_using_virtual_board/spynnaker.cfg
- unittests/test_sata_connectors/spynnaker.cfg
- unittests/test_sata_connectors/test_sata_2_different_boards_valid_board_address.py
- unittests/test_spinnaker_link_connectors/spynnaker.cfg
- unittests/test_spinnaker_link_connectors/test_spinnaker_link_2_different_boards_valid_board_address.py
- unittests/test_using_virtual_board/spynnaker.cfg
- unittests/test_using_virtual_board/test_debug_mode/spynnaker.cfg
- unittests/test_using_virtual_board/test_do_not_allow_violate/spynnaker.cfg
- unittests/test_virtual_board_no_vertices_supported/spynnaker.cfg
part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/256
> Version flexible Virtual Machine

- spynnaker/pyNN/extra_algorithms/spynnaker_neuron_network_specification_report.py
While running tsp_test.py in debug mode I noticed that while network_graph.gv.png it appeared to hang.
Fix 1.
rather than being part of the progress bar there is now a long message saying generating,
I also noticed that by doing an edge per synapse info it was generating a lot of identical edges between the same two nodes.
Fix 2. 
Make a set before making dot edges to avoid these duplicates.
tested with tsp_test.py and the resulting png generates relatively fast and somewhat readable. (When zoomed in)
> dont genernate duplicate edges

- unittests/test_sata_connectors/spynnaker.cfg
- unittests/test_spinnaker_link_connectors/spynnaker.cfg
Part of https://github.com/SpiNNakerManchester/SpiNNMachine/pull/260
> these tests need FPGSa and Spinnaker link defined

- neural_modelling/makefiles/neuron/Makefile
tested manually as not tested by actions of Jenkins
> more neurons possible in debug

- test_whole_board/test_whole_board.py
Part of https://github.com/SpiNNakerManchester/SpiNNMan/pull/401
> simplify the spalloc keep alive

- spynnaker_integration_tests/test_stdp/test_STDP_triplet_additive.py
part of https://github.com/SpiNNakerManchester/IntegrationTests/pull/272
> PyNNExamples

- .github/workflows/c_actions.yml
- proxy_integration_tests/test_python_debug/check_debug.py
- spynnaker_integration_tests/test_debug_mode/check_debug.py
Test adjustments for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1201
> Limit use of advance monitors for loading

- spynnaker/pyNN/models/neuron/synaptic_matrix_app.py
- spynnaker/pyNN/utilities/neo_buffer_database.py
Part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1209
get_last_data_by_placement remove as no longer needed
_get_region_id inow also returns is_recording so that value must be ignored
> recording data fixes

- spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py
- spynnaker/pyNN/models/neural_projections/connectors/all_but_me_connector.py
- spynnaker_integration_tests/test_debug_mode/check_debug.py
- spynnaker_integration_tests/test_debug_mode/test_python_debug/test_debug.py
test for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1217
fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/1493
Also a constant renamed missed for changing an earlier pr
> Skip gathererer

- spynnaker_integration_tests/test_external_devices/test_spike_run_forever_again.py
Test of SpiNNakerManchester/SpiNNFrontEndCommon#1223
> Allow run forever pause

- spynnaker/pyNN/models/spike_source/spike_source_array_machine_vertex.py
- spynnaker_integration_tests/test_external_devices/test_spike_run_forever_again.py
part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1230
breaks https://github.com/SpiNNakerManchester/sPyNNaker/blob/master/spynnaker_integration_tests/test_external_devices/test_spike_run_forever_again.py
> simplify is_in_range

- neural_modelling/makefiles/neuron/Makefile
- spynnaker_integration_tests/test_external_devices/test_spike_run_forever_again.py
> Get current time support

- spynnaker/pyNN/connections/spynnaker_poisson_control_connection.py
- spynnaker/pyNN/external_devices_models/machine_munich_motor_device.py
- spynnaker/pyNN/extra_algorithms/redundant_packet_count_report.py
- spynnaker/pyNN/models/neuron/master_pop_table.py
- spynnaker/pyNN/models/neuron/population_machine_local_only_combined_vertex.py
- spynnaker/pyNN/models/neuron/population_machine_vertex.py
- spynnaker/pyNN/models/neuron/population_neurons_machine_vertex.py
- spynnaker/pyNN/models/neuron/population_synapses_machine_vertex_lead.py
- spynnaker/pyNN/models/neuron/population_synapses_machine_vertex_shared.py
- spynnaker/pyNN/models/spike_source/spike_source_array_machine_vertex.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
- spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
- spynnaker/pyNN/utilities/data_population.py
- spynnaker/pyNN/utilities/neo_buffer_database.py
- unittests/test_pop_views_assembly/test_data_population.py
Part of https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1245
SQLiteDB methods execute and execute_many removed as kwargs methods
fixed a big found in  DataPopulation by typing
> Typing for FEC

- spynnaker_integration_tests/test_power_monitoring/test_power_mon.py
cleaner version of https://github.com/SpiNNakerManchester/sPyNNaker/pull/1513
tested locally
> cleaner test  for multiple energy

- spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_neurons_synapses.py
part of https://github.com/SpiNNakerManchester/PACMAN/pull/588
> use AbstractVertex rather than Union

- spynnaker/plot_utils.py
- spynnaker/pyNN/models/neural_projections/connectors/all_but_me_connector.py
- spynnaker/pyNN/models/neuron/abstract_population_vertex.py
- spynnaker/pyNN/models/neuron/local_only/local_only_convolution.py
- spynnaker/pyNN/models/neuron/population_machine_neurons.py
- spynnaker/pyNN/models/neuron/synapse_io.py
- spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
- spynnaker/pyNN/utilities/neo_buffer_database.py
> Fix some new typing errors

- spynnaker_integration_tests/test_auto_pause_and_resume_tests/test_run_forever_recorded/test_run_forever_recorded.py
Make this test actually end!
Testing with https://github.com/SpiNNakerManchester/IntegrationTests/pull/308
> Fix run forever test

- spynnaker/pyNN/extra_algorithms/neuron_expander.py
- spynnaker/pyNN/extra_algorithms/synapse_expander.py
- spynnaker_integration_tests/test_external_devices/test_spike_run_forever_again.py
Part of:
- SpiNNakerManchester/SpiNNMan#432
> Use more processes

- spynnaker_integration_tests/test_connectors/test_connectors.py
removes an unneeded line which confuses mypy
found by new mypy 1.16
> remove unneeded set to None

- spynnaker/pyNN/external_devices/__init__.py
- spynnaker/pyNN/models/populations/population.py
- spynnaker/pyNN/models/populations/population_view.py
- spynnaker/pyNN/models/recorder.py
- unittests/test_doc_checker.py
Part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/321
renamed recorder.csv_neo_block to  write_data
> Doc checker

- .github/workflows/add_prs_to_project.yml
Add a workflow to add PRs to project automatically
> Add prs to project
