SpiNNakerManchester/sPyNNaker

spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
spynnaker/pyNN/spinnaker.py

This one may be slightly more controversial, but it speeds up generating big list connectors pretty massively. The previous version supported some stuff I see no sign of in the PyNN spec (http://neuralensemble.org/trac/PyNN/wiki/API-0.7#FromListConnector) - I'm not entirely certain how distributions could be validly used in the context of a list connector, but the support for the alternative 
```
[
[pre_idx0, pre_idx1, ..., pre_idxN], 
[pre_idx1, pre_idx2, ..., pre_idxN], 
[weight0, weight1, ..., weightN], 
[delay0, delay1, ..., delayN]
]
```
Format could be supported fairly trivially if there's some desire for it.

List connector optimisation

---

spynnaker/pyNN/spinnaker.py
spynnaker/pyNN/utilities/conf/spynnaker.cfg.template
spynnaker/spynnaker.cfg

fixes a issue if you have a spinn-4/ spinn-5 board and havent got the bmp connected

adds the ability to not autodetect the bmp if needed by the end user

---

spynnaker/pyNN/models/spike_source/spike_source_array.py

SpikeSourceArray did not specify a default value for spike_times
in its constructor. This caused sPyNNaker to crash with the
weird exception
File "sPyNNaker/spynnaker/pyNN/models/pynn_population.py", line 79, in __init__
self._vertex = cellclass(**cellparams)
TypeError: __init__() takes at least 5 arguments (5 given)
if an empty parameter dictionary was passed to the Population
constructor (which supposedly should not happen):
sim.Population(10, sim.SpikeSourceArray, {})
This fix simply adds the missing default value to the spike_times
parameter. Note, that the parameter order in the
SpikeSourceArray constructor was altered.

Add default value to SpikeSourceArray spike_times

---

spynnaker/pyNN/models/neural_projections/projection_machine_edge.py

I need SynapseInformation from Machine edges for some filtering. Added a getter for it so I don't access private variables.

Getter for SynapseInformation in MachineEdge

---

neural_modelling/src/neuron/neuron.c
spynnaker/pyNN/models/neuron/abstract_population_vertex.py
spynnaker/pyNN/models/neuron/synaptic_manager.py

Added the fix for neuron spikes to enforce them to be spread out.  Note that this is slightly different that that done in the other similar modules as it doesn't use the SARK busy-wait procedure.  This is because the SARK procedure doesn't take account of interrupts in the wait time, which matters more in the neuron model than in the other models.

Spread neuron spikes

---

setup.py
spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py
spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
spynnaker/pyNN/models/neural_projections/connectors/from_file_connector.py
spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
spynnaker/pyNN/models/neural_projections/connectors/small_world_connector.py
spynnaker/pyNN/models/neuron/connection_holder.py
spynnaker/pyNN/overridden_pacman_functions/algorithms_metadata.xml
spynnaker/pyNN/spinnaker.py
spynnaker/pyNN/utilities/spynnaker_connection_holder_generations.py
spynnaker/pyNN/utilities/spynnaker_neuron_network_specification_report.py
spynnaker/pyNN/utilities/spynnaker_synaptic_matrix_report.py
spynnaker/spynnaker.cfg

supports using graphviz to get a diagram of the network being loaded (after filtering and machine graph generation). 
requires the end user to have installed graphviz, so the main installation pages needs a update when this is merged in.

Graph diagram generation and synaptic read optimisation

---

.travis.yml

This is the set of changes needed to support just running the integration tests as part of a nightly build.

Support for only running the integration tests in a nightly build

---

.travis.yml

This adds enforcement of C style rules.
All files matching `*.[ch]` below `neural_modelling` pass.

C code-style enforcement

---

spynnaker/pyNN/models/spike_source/spike_source_poisson.py

- followed instructions by AR to fix issue when spikes_per_timestep is
zero or small.
Followed instructions in issue: https://github.com/SpiNNakerManchester/sPyNNaker/issues/271
Tested against all examples I can find that use SpikeSourcePoisson, no problems.  Not sure whether we have any example that uses a low Poisson rate as described in the issue - couldn't find any.

Add low rate value check

---

spynnaker/plot_utils.py

- noticed this from error thrown at the end of integration_test in
sPyNNaker7/p7_integration_tests/test_various
test_synfire_izk_curr_exp.py when attempting to plot using subplot

matplotlib subplot index starts at 1, not 0

---

spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py

Enabling a delay of '0' to be specified as an integer, but still be clipped to a single timestep (rather than zero, which results in a 16 timestep delay).

Fix delays int 0

---

spynnaker/pyNN/models/neuron/synaptic_manager.py

Added a multiplication to avoid too much SDRAM being used in very large networks (comes up with the Microcircuit example)

fix sdram overuse

---

spynnaker/pyNN/models/neuron/threshold_types/threshold_type_maass_stochastic.py

Going through documentation and spotted this spelling mistake

Rename MASS to MAASS

---

spynnaker/pyNN/models/common/eieio_spike_recorder.py
spynnaker/pyNN/models/common/multi_spike_recorder.py
spynnaker/pyNN/models/common/recording_utils.py
spynnaker/pyNN/models/neuron/master_pop_table_generators/master_pop_table_as_binary_search.py
spynnaker/pyNN/models/neuron/synaptic_manager.py

I was reading through the [struct documentation](https://docs.python.org/2/library/struct.html#classes) and I noted that it said
> "Creating a Struct object once and calling its methods is more efficient than calling the struct functions with the same format since the format string only needs to be compiled once."
which I think is highly relevant to us, especially in an area that is a bit of a bottleneck. And this is a feature of a core Python library that we already use too.

Encoding and decoding of binary data should use precompiled patterns.

---

neural_modelling/src/neuron/c_main.c
spynnaker/pyNN/models/common/abstract_uint32_recorder.py
spynnaker/pyNN/models/neuron/abstract_population_vertex.py
spynnaker/pyNN/spynnaker.cfg

This mostly fixes what happens when the data contains missing sections, by adding a "NaN" value at these points.  This appears to work correctly when graphing, although the graphs then stop at the first NaN.

Fix buffered out

---

spynnaker/pyNN/models/neuron/builds/if_curr_alpha.py

Small fix to add a default entry to the set max atoms per core function (which is called on reset without an argument)

Fix if curr alpha max atoms per core default

---

spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
unittests/model_tests/test_connectors.py

Fix of issue https://github.com/SpiNNakerManchester/sPyNNaker/issues/435
Associated pull requests for sPyNNaker7 and sPyNNaker8 should be done at the same time.
A few observations:
- the code which existed to do a random permutation does not seem to work as I expected it to, so I have left the randomness up to the numpy.random.choice function; if preferred, I can look at this code (commented out in e.g. the fixed number pre-connector lines 62-93) again?
- I have added some tests in sPyNNaker7 and sPyNNaker8; I noted while playing with population size on these (to check this still works when a population is divided between multiple cores) that increasing the population size leads to more timer tick and weight saturation warnings.  Is this normal or expected behaviour?
- please check my …

Fixed number connectors

---

neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_nearest_pair_impl.h

Fix to make nearest pair rule operate only on the first post spike after a pre spike

Fix nearest pair so only first post spike after pre spike is used

---

.travis.yml

This is a workaround for https://github.com/travis-ci/travis-ci/issues/4704 that resets stdout so that it is in blocking mode, which is what most normal command line tools expect.
The script to actually apply the fix is [this](https://github.com/SpiNNakerManchester/SupportScripts/blob/master/travis_blocking_stdout.py).
***We should not have had to do this!*** _Seriously, ugh!_

Workaround for failing Travis builds due to nonblocking stdout!

---

neural_modelling/src/neuron/plasticity/common/post_events.h
neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c

I wrote these functions today whilst debugging the post-synaptic event history data-structure. They're a useful tool for debugging, and so I think they're useful to have in the main toolchain.

Plasticity window printing

---

spynnaker/pyNN/models/neuron/synaptic_manager.py

Without this comparison to the individual biggest weight, it's possible to return zero as the max weight when using a Poisson spike source, and subsequently write a weight to SpiNNaker of zero, if it can't be represented with a single integer bit (as the shift is zero). 
It seems to make sense, as regardless of Poisson rate, the ring buffers should always be scaled to take the single biggest individual weight.

add maximum weight check to poisson max weight calculation

---

neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
neural_modelling/src/neuron/synapse_row.h
neural_modelling/src/neuron/synapses.c
neural_modelling/src/neuron/synapses.h
spynnaker/pyNN/models/neuron/abstract_population_vertex.py
spynnaker/pyNN/models/neuron/builds/if_cond_exp_base.py
spynnaker/pyNN/models/neuron/builds/if_cond_exp_stoc.py
spynnaker/pyNN/models/neuron/builds/if_curr_alpha.py
spynnaker/pyNN/models/neuron/builds/if_curr_delta.py
spynnaker/pyNN/models/neuron/builds/if_curr_dual_exp_base.py
spynnaker/pyNN/models/neuron/builds/if_curr_exp_base.py
spynnaker/pyNN/models/neuron/builds/if_curr_exp_ca2_adaptive.py
spynnaker/pyNN/models/neuron/builds/izk_cond_exp_base.py
spynnaker/pyNN/models/neuron/builds/izk_curr_exp_base.py
spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_static.py
spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
spynnaker/pyNN/models/neuron/synapse_io/synapse_io_row_based.py
spynnaker/pyNN/models/neuron/synaptic_manager.py
unittests/model_tests/neuron/test_synaptic_manager.py

This adjusts the code to use n_neurons instead of passing down the max feasible atoms per core.  This not only appears to work correctly, but it also reduces the number of instructions by 2 within that part of the code!  Not sure why this should be, but it works in any case...
This has the advantage that the ring buffer size is now related to the number of neurons per core.  This doesn't make it as small as it can be (it is sized to the next closest power of 2 of the number of neurons -
to make it exact would require other changes to be made in the future), but the reduction is still useful.
Note that this is a pull request to pass_down_max_feasible_atoms_per_core.  As such, it currently fails due to a dependency on spinn_common branch by the same name (but different to the name of this …

Updates to make the code use n_neurons for ring buffer sizing

---

spynnaker/pyNN/models/neural_projections/connectors/__init__.py
spynnaker/pyNN/models/neural_projections/connectors/array_connector.py

Work to support using an ArrayConnector on the toolchain; basically, as simple as it sounds: the user supplies a 2D array of neuron IDs specifying the connections and this is simply passed into the synaptic blocks as required.

Array connector

---

spynnaker/pyNN/models/neural_projections/connectors/array_connector.py

This should now work for all arrays, not just arrays that are the same size as the number of neurons.  I've updated the integration test in sPyNNaker8 to test one array that is not the same size, but we perhaps should bullet-proof this a bit more by testing it with all sorts of different arrays...

Update ArrayConnector to work with all arrays

---

spynnaker/pyNN/models/abstract_models/abstract_population_settable.py
spynnaker/pyNN/models/neuron/abstract_population_vertex.py
spynnaker/pyNN/models/neuron/additional_inputs/additional_input_ca2_adaptive.py
spynnaker/pyNN/models/neuron/input_types/input_type_conductance.py
spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py
spynnaker/pyNN/models/neuron/neuron_models/neuron_model_leaky_integrate.py
spynnaker/pyNN/models/neuron/synapse_types/synapse_type_alpha.py
spynnaker/pyNN/models/neuron/synapse_types/synapse_type_delta.py
spynnaker/pyNN/models/neuron/synapse_types/synapse_type_dual_exponential.py
spynnaker/pyNN/models/neuron/synapse_types/synapse_type_exponential.py
spynnaker/pyNN/models/neuron/threshold_types/threshold_type_maass_stochastic.py
spynnaker/pyNN/models/neuron/threshold_types/threshold_type_static.py
spynnaker/pyNN/utilities/ranged/__init__.py
spynnaker/pyNN/utilities/ranged/spynakker_ranged_dict.py
unittests/model_tests/neuron/test_neural_parameter.py

Let the classes in spynnaker.pyNN.utilities.ranged be found easily. (Provide a non-empty `__init__.py` and load through that elsewhere.)

Shorten some module names.

---

spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py

Started looking at weights and delays in connectors, in relation to https://github.com/SpiNNakerManchester/sPyNNaker/issues/519; have added warnings for now that the values in a projection get overwritten if the same connector is re-used.  Can continue working on this, but if anyone else wants to jump in on it at some point then feel free...

Add warnings for now that values get overwritten

---

spynnaker/pyNN/models/common/eieio_spike_recorder.py

Actual fix for bug discovered by @SimonDavidson 
Return an empty array with the correct shape

on no spikes returns an empty shaped array

---

requirements-test.txt

Travis was complaining about the pytest version after the latest merge to master I did, so I've updated it.

update pytest to version required for timeout

---

spynnaker/pyNN/models/neuron/neuron_models/neuron_model_leaky_integrate_and_fire.py

Unit tests in sPyNNaker8 (at least) were failing in python3, as numpy.ceil returns a float and tau_refrac_timesteps is an integer.

tau_refrac_timesteps is an integer

---

neural_modelling/src/neuron/neuron.c
spynnaker/pyNN/models/neuron/implementations/abstract_standard_neuron_component.py
spynnaker/pyNN/models/neuron/implementations/ranged_dict_vertex_slice.py
spynnaker/pyNN/models/neuron/implementations/struct.py
spynnaker/pyNN/models/neuron/neuron_models/abstract_neuron_model.py

We mustn't have tested some branch that was merged recently that well because multirun was broken (as originally reported in https://github.com/SpiNNakerManchester/sPyNNaker8/issues/165).  This PR and the associated one in FrontEndCommon - https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/352 - fixes it.

Really make sure that we reference the correct memory when storing

---

spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py

There is a misalignment between the C code struct, and what the Python code writes, meaning you end up with incorrect neural dynamics.
Also the global time step which gets written is too big, so you get strange behaviour after the first spike.

Reorder variables to match C code

---

neural_modelling/src/neuron/models/neuron_model_izh_impl.c

This patch is fixing an issue with the constants that cannot be exactly represented as accums and are rounded down by GCC (as opposed to rounding to the nearest accum). This reduces the error and significantly improves the spiking lag reported in https://www.ncbi.nlm.nih.gov/pubmed/26313605.
Replicating the experiment from the paper, the spikes that should happen at 101ms, 201ms, 301ms... and so on at each 101st boundary, have a lag. Here are first 29 spikes from the experiment with DC current:
104.9   207.9   310.9   413.9   516.9   619.8   722.7   825.7   928.8 1031.8  1134.8  1237.9  1341.   1444.1  1547.2  1650.3  1753.4  1856.5 1959.5  2062.4  2165.3  2268.3  2371.4  2474.4  2577.4  2680.5  2783.6 2886.7  2989.8
I.e. spike 1 has a lag of 3.9ms and spike 29 has a lag of 88.8ms.
After …

Improvement to the Izhikevich ODE solver

---

spynnaker/pyNN/models/common/neuron_recorder.py

Fix for https://github.com/SpiNNakerManchester/sPyNNaker/issues/570
Neuron.c 
save a recoing array for all neurons.
out_spikes_initialize(n_neurons)
But only writes the neurons recording.
out_spikes_record(SPIKE_RECORDING_CHANNEL, time, n_spike_recording_words,             recording_done_callback))
This is the best solution as no need to write and read back the overflow word.
Adjusted the python to not expect and then throw away that word.

neuron.c is smarter and does not save overflow to

---

neural_modelling/makefiles/neuron/neural_build.mk
neural_modelling/src/neuron/additional_inputs/additional_input_ca2_adaptive_impl.h
neural_modelling/src/neuron/plasticity/stdp/maths.h

Change implemented to enable building of a neuron model with non-standard neuron implementation and STDP.
This update works for me!

Remove synapse type header as not now needed

---

spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py

Fix for issue https://github.com/SpiNNakerManchester/sPyNNaker/issues/605 
Note: this wasn't showing up for FixedNumberPre and FixedNumberPost because they don't use the on-chip expander yet, whereas this connector does - so it was never (with defaults turned on) getting to the point where it should have thrown the exception that was written in there originally (before the expander existed).  I've made it throw an exception now before it even gets to expanding.

Throw an exception if requested number of synapses is too large

---

spynnaker/pyNN/models/common/neuron_recorder.py

Bugfix if user asks for duplicates in recording indexes.
Note: If the users sets recording on a view gets data on the whole population the data comes out in numerical order. If they also call get_data on the view (or a similar one) goes out in the view order and can include duplicates.

Fix duplicate error and sort for consitency.

---

neural_modelling/src/synapse_expander/matrix_generators/matrix_generator_static.h
neural_modelling/src/synapse_expander/param_generators/param_generator_exponential.h
neural_modelling/src/synapse_expander/param_generators/param_generator_normal.h
neural_modelling/src/synapse_expander/param_generators/param_generator_normal_clipped.h
neural_modelling/src/synapse_expander/param_generators/param_generator_normal_clipped_to_boundary.h
neural_modelling/src/synapse_expander/param_generators/param_generator_uniform.h
spynnaker/pyNN/models/neuron/synaptic_manager.py
spynnaker/pyNN/models/utility_models/synapse_expander/synapse_expander.py

Fixes a couple of issues with the synaptic expander, namely that things weren't being free'd completely (and so sometimes the heap and stack would clash), and that where multiple projections existed between a pair of populations but the delay stages were different, incorrect delays could be generated.

Fix synapse expander

---

neural_modelling/src/neuron/threshold_types/threshold_type_maass_stochastic.h
spynnaker/pyNN/models/neuron/threshold_types/threshold_type_maass_stochastic.py

Fixes issue #551; it's better to have this one in Python anyway, as that's one less arithmetic op in the computation (and who doesn't like avoiding a compiler crash?!)

Move negation of timescale factor into Python

---

spynnaker/pyNN/models/neuron/synaptic_manager.py

Issue explained in more detail https://github.com/numpy/numpy/issues/13653  
Basically, numpy.float64 has a ` __getitem__` attribute and the check of whether `spikes_per_second` is iterable passes and `max(spikes_per_second)` crashes with the error:
```
Traceback (most recent call last):
File "C:/Work/phd/sundry/npfloat64_bug.py", line 8, in <module>
print(max(y))
TypeError: 'numpy.float64' object is not iterable
```
``` 
import sys, numpy; print(numpy.__version__, sys.version)
import numpy as np
x = np.float(80)
if hasattr(x, "__getitem__"):
print(max(x))
y = np.float64(80)
if hasattr(y, "__getitem__"):
print(max(y))
``` 
Numpy and sys versions: 1.16.2 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 24 2018, 00:16:47) [MSC v.1916 64 bit (AMD64)]
Using `np.max()` instead of `max()`  behaves correctly.

work-around for numpy.float64 having __getitem__

---

spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
spynnaker/pyNN/models/pynn_projection_common.py
unittests/mocks.py

Fix for https://github.com/SpiNNakerManchester/sPyNNaker/issues/618 - the case where the delays were an array containing mixed values where some required delay extensions and some did not was not dealt with correctly.

Compare using both the max and the min, otherwise mixed cases are missed

---

spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py

Fix for https://github.com/SpiNNakerManchester/sPyNNaker/issues/617 - the calls to _generate_weights and _generate_delays needed to be updated when the user passes in arrays in the (Static)Synapse.

Deal with input arrays in generate_weights and generate_delays correctly

---

neural_modelling/src/spike_source/poisson/spike_source_poisson.c

Fix for https://github.com/SpiNNakerManchester/sPyNNaker/issues/553 which for some reason hadn't been done yet.

Use the struct parameter rather than the global value

---

spynnaker/pyNN/models/pynn_projection_common.py

It's a bit hacky, perhaps, but a way of getting round the TypeError on this line when using a RandomDistribution for the delays needs to happen in order for e.g. the microcortical column to run.  It is extremely unlikely that the edge-case problem that this line solved originally will occur when using a RandomDistribution.

Fix to get round error when delay is a RandomDistribution

---

unittests/connector_tests/test_csa_connector.py

Occasionally this test might return an empty block, so update the test to include that case.

Fix csa random test

---

spynnaker/pyNN/models/neuron/synaptic_manager.py

The fix (already in master now) at https://github.com/SpiNNakerManchester/sPyNNaker/pull/667 wasn't comprehensive enough and caused failures in most cases with n_neurons > 255 (found by the cron-job on Jenkins in, for example p8_integration_tests/quick_test/test_connectors/test_all_to_all_connector.py).  This fix should ensure that all cases now work correctly.

Fix issues with synapse_info for n_neurons > 255

---

neural_modelling/makefiles/neuron/neural_build.mk

I'm able to build all binaries with time optimisation enabled therefore suggest this be made default given the core processing performance gains it provides.
Any binaries that cannot be built with a time optimisation compiler flag can redefine the FEC_OP value in their own make files to OSPACE

set default to time optimistation in neural make file

---

requirements-test.txt
spynnaker/pyNN/models/abstract_pynn_model.py
spynnaker/pyNN/models/defaults.py
unittests/model_tests/neuron/test_abstract_neuron_impl.py
unittests/model_tests/neuron/test_defaults.py
unittests/test_populations/test_vertex.py

A replacement for #640 which uses the existing infrastructure to check for the assignment of initial values through the constructor.  Note that this version keeps the values of the initial values in tact, so the default_initial_values still works.

Initial values 2

---

requirements.txt
spynnaker/pyNN/models/neural_projections/connectors/csa_connector.py

csa causes problems in readthedocs due to its dependency on matplotlib
This (slighlty sticky paster) does
1. Removes csa from requirements
2. Adds it to setup but only if not in READTHEDOCS  (also for spynakker8)
https://github.com/SpiNNakerManchester/sPyNNaker8/pull/237
3. Delays the ModuleNotFoundError until a csaconnector is created 
Note: as the typical way to create a CSAConnector is with a csa object  for example: CSAConnector(csa.oneToOne) It is likely the script will need to also do import csa   which will fail there.
tested with:
https://spinnaker8manchester.readthedocs.io/en/readthedocs/

exclude csa

---

unittests/model_tests/neuron/test_neural_parameter.py

Using the same filename in each test can lead to uninformative failures. Use a temporary file instead.

Emergency fix: make sure tests can run in parallel

---

neural_modelling/src/neuron/implementations/neuron_impl_standard.h

Following https://github.com/SpiNNakerManchester/spinnaker_tools/pull/95, you can't now specify null arguments in spin1_memcpy(...).  This PR fixes that in cases where we have particular neuron components that (could have) empty structs.

Deal with compiler warnings for null arguments to spin1_memcpy

---

spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
spynnaker/pyNN/utilities/utility_calls.py

Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/587
It seems to simply be the case that this was being done correctly for other probabilistic connectors, but not for the FixedProbabilityConnector.  I haven't seen any failures in this test since adjusting the chance values to those used in other connectors.  (Given that it is probabilistic, it's possible this test will fail very occasionally; if we see it failing again as often as it was before then my suggestion would be to make the chance values even smaller than they already are).
[It would also be instructive to check whether this causes any problems with SDRAM requirements for larger jobs - I've tested a few but by no means exhaustively.]

Fixed prob connector fix

---

neural_modelling/src/robot_motor_control/robot_motor_control.c

Don't know how this was missed or what uncovered it, but the call here didn't match the API correctly so it was failing to compile.

Match simulation API

---

neural_modelling/src/spike_source/poisson/spike_source_poisson.c

Minor fix that uses the correct variable in the comparison when setting live rates (missed this one).  This should fix the error in the daily integration tests.

Fix poisson

---

neural_modelling/src/spike_source/poisson/spike_source_poisson.c

This was still wrong (and must have been wrong for some time!).  This should fix it as it now does the same thing that the host does.  This also fixes the fast-but-not-faster case after setting a faster rate previously (it resets the faster item to 0 to make sure it doesn't get used any more).

Fix slow rate live setting

---

neural_modelling/makefiles/neuron/neural_build.mk
neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c

Not sure how many people ever bother to compile with `SPYNNAKER_DEBUG=DEBUG` nowadays, but if they do at the moment then it won't work - this fixes that.  (Note however that at the moment compiling with this puts `IF_curr_exp_stdp_mad_pair_additive_structural` and `IF_cond_exp_stdp_mad_pair_additive_structural` over the ITCM limit - I guess it'll be worth trying this again once https://github.com/SpiNNakerManchester/sPyNNaker/pull/687 is merged.)
A related question, is `FEC_DEBUG=DEBUG` intended just for FrontEndCommon, or should it work from sPyNNaker as well? (i.e. should you be able to do `make SPYNNAKER_DEBUG=DEBUG FEC_DEBUG=DEBUG` from sPyNNaker?  I tried it and it complained about something related to assert(...), which led me down a rabbit-hole of confusion in spinn_common and …

Make synapse printing code inside LOG_DEBUG work again

---

neural_modelling/src/synapse_expander/delay_expander.c
spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
spynnaker/pyNN/models/utility_models/delays/delay_generator_data.py

Fix to make integration test in https://github.com/SpiNNakerManchester/sPyNNaker8/pull/270 work.  Basically, the delay_expander was performing the work in a different order to the synapse_expander, and this was causing it to fail in the specific instance outlined in that test.
While I was there I also (prompted by what @Christian-B was trying to do) fixed the FixedNumberPre- and Post- so that they should now work correctly at 1 neuron per core, rather than giving synaptic memory size errors.

Synapse expander bug

---

spynnaker/pyNN/spynnaker_external_device_plugin_manager.py

Found this when trying to figure out issues on a different branch.  The only thing I think this affected directly (on master at least) was IntroLab/sudoku, where it tries to set "tag", and this then gets mixed up with "board_address".

Put function call arguments in the correct order

---

spynnaker/pyNN/models/common/neuron_recorder.py
spynnaker/pyNN/models/neuron/abstract_population_vertex.py

Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/725
Note: get_n_cpu_cycles has NOT been changed as it is already wrong and most of the cpu_cycles per neuron happen regardless of if the variable is actually recording

calc recordered variable per slice/ machinevertex

---

spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_pfister_spike_triplet.py
spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_spike_nearest_pair.py

Seems as though these were missed during the STDP upgrade.

LUTs now work at timestep != 1.0

---

neural_modelling/src/spike_source/poisson/spike_source_poisson.c

Just a small change to stop the compiler spitting out warnings when doing a standard compilation (i.e. not in debug mode).

Prevent warnings when not compiling in debug mode

---

spynnaker/pyNN/models/neuron/plasticity/stdp/common/plasticity_helpers.py
spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_vogels_2011.py

Math magic computes the length of the array without a loop.
Numpy magic fills out the array rapidly.

Use math magic and numpy magic to compute LUTs efficiently

---

spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py

Parameter names were confusing; hopefully this makes them a bit clearer.

Rename kernel parameters for starts & steps to be less confusing

---

neural_modelling/src/synapse_expander/common_kernel.c

Use the `div` function (from stdlib.h) because that won't degrade in performance horribly when the dividend is significantly larger than the divisor.

More efficient division algorithm

---

spynnaker/pyNN/overridden_pacman_functions/algorithms_metadata.xml

GraphEdgeFilter needs a token as otherwise no way to know for sure it has run.

Edge Filtered token

---

neural_modelling/src/neuron/c_main.c
neural_modelling/src/neuron/synapses.c
neural_modelling/src/neuron/synapses.h
spynnaker/pyNN/models/neuron/abstract_population_vertex.py

Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/766
This is probably overkill, but the alternative is to ask the machine to report back that there are (delayed) spikes left over that have not yet been processed, and I'm not sure that's any better.

Deal with reset case with left over delayed spike

---

spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
spynnaker/pyNN/models/neural_projections/connectors/small_world_connector.py

Overnight failure of the small-world connector test (http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/sPyNNaker8_Cron_Job/detail/sPyNNaker8_Cron_Job/355/pipeline) made me go back and look at the actual connector and modify it to match PyNN (and so that rngs can actually be passed through...).

Update argument list for SmallWorldConnector to match PyNN better

---

spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
spynnaker/pyNN/models/neuron/synapse_io.py
unittests/model_tests/neuron/test_get_max_synapses.py

Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/759
@pabogdan does this help with what you were seeing?  (If not can you create a minimal example that fails?)

Add safety check to prevent underflow in _get_max_row_length

---

spynnaker/pyNN/models/recording_common.py

The correct place for the instrumentation is in FEC now that buffers are managed using a database. **NOTE THAT THIS CHANGES PUBLISHED TIMINGS** because it means that extraction of spike data will now be measured (correctly!) as data extraction.
This is a bugfix linked to https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/569

Remove incorrect timing measurement instrumentation

---

neural_modelling/src/neuron/implementations/neuron_impl_eprop_adaptive.h
neural_modelling/src/neuron/models/neuron_model_eprop_adaptive_impl.c
spynnaker/pyNN/models/neuron/neuron_models/neuron_model_eprop_adaptive.py

Fix pause-and-resume for eprop neuron; basically, the issue was that the global parameters were being regularised again on the second run after pausing.  It's possibly a bit confusing, but the current state of pause-and-resume (binary gets paused, and then starts again from the beginning of c_main()) means that initialise() gets called again at the start of the second run, so anything that should only happen on the first run needs to be guarded against the second time round.

Fix pause-and-resume for eprop neuron model

---

.travis.yml
neural_modelling/src/neuron/implementations/neuron_impl_standard.h
spynnaker/pyNN/external_devices_models/external_device_lif_control.py
spynnaker/pyNN/external_devices_models/threshold_type_multicast_device_control.py
spynnaker/pyNN/models/neuron/abstract_pynn_neuron_model_standard.py
spynnaker/pyNN/models/neuron/additional_inputs/additional_input_ca2_adaptive.py
spynnaker/pyNN/models/neuron/implementations/abstract_standard_neuron_component.py
spynnaker/pyNN/models/neuron/implementations/neuron_impl_standard.py
spynnaker/pyNN/models/neuron/input_types/input_type_conductance.py
spynnaker/pyNN/models/neuron/input_types/input_type_current.py
spynnaker/pyNN/models/neuron/input_types/input_type_current_semd.py
spynnaker/pyNN/models/neuron/input_types/input_type_delta.py
spynnaker/pyNN/models/neuron/neuron_models/abstract_neuron_model.py
spynnaker/pyNN/models/neuron/neuron_models/neuron_model_izh.py
spynnaker/pyNN/models/neuron/neuron_models/neuron_model_leaky_integrate_and_fire.py
spynnaker/pyNN/models/neuron/synapse_types/synapse_type_alpha.py
spynnaker/pyNN/models/neuron/synapse_types/synapse_type_delta.py
spynnaker/pyNN/models/neuron/synapse_types/synapse_type_dual_exponential.py
spynnaker/pyNN/models/neuron/synapse_types/synapse_type_exponential.py
spynnaker/pyNN/models/neuron/synapse_types/synapse_type_semd.py
spynnaker/pyNN/models/neuron/threshold_types/threshold_type_maass_stochastic.py
spynnaker/pyNN/models/neuron/threshold_types/threshold_type_static.py
unittests/test_populations/test_vertex.py

Requested by @pabogdan.  This allows a neuron model to split its time step into multiple calls to the updates, so it is more precise, whilst the time step is still kept at a lower rate.  This can be configured per-population for any model using the standard implementation (with the components).
Also see changes in SpiNNakerManchester/sPyNNaker8NewModelTemplate#54
Tested by SpiNNakerManchester/sPyNNaker8#398

Multi time step

---

.travis.yml
spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
spynnaker/pyNN/protocols/munich_io_spinnaker_link_protocol.py

The connection estimates were incorrect for the FixedNumberPostConnector; this fixes it so that scripts that should work now do, rather than failing because of an overestimate of the synaptic row length required.
Additional test added as a check for this in the future: https://github.com/SpiNNakerManchester/sPyNNaker8/pull/406

Fix the connection estimates for FixedNumberPostConnector

---

spynnaker/pyNN/models/neuron/abstract_population_vertex.py

Most likely an oversight in the recent-ish multi-run / reset changes, as this is not a standard PyNN function.  This fixes the issue at https://github.com/SpiNNakerManchester/sPyNNaker8/issues/331.
Have added the script from @ej159 as a test in https://github.com/SpiNNakerManchester/sPyNNaker8/pull/409.

Reload neuron parameters after setting initial value

---

neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h

This prevents GCC from deciding that it has to convert a simple copy of a four-byte structure into a call to `memcpy()`, a function that is hundreds of bytes long on ARM. This is the only place in our code where this was happening, and it was all because the compiler was thinking “but _what if_ this field happens to have a non-aligned value put in it, hmm?” when we can outright prove ourselves (but not quite to the compiler's satisfaction) that this never happens.
The portable(-ish) syntax for doing this is horrible.

Magic, with __builtin_assume_aligned()!

---

neural_modelling/src/neuron/structural_plasticity/synaptogenesis/formation/formation_distance_dependent_impl.h
neural_modelling/src/neuron/structural_plasticity/synaptogenesis/partner_selection/last_neuron_selection_impl.h
neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h
neural_modelling/src/neuron/structural_plasticity/synaptogenesis/topographic_map_impl.c
spynnaker/pyNN/models/neuron/structural_plasticity/synaptogenesis/formation/distance_dependent_formation.py

Removes type conversion and division making the code size much smaller.  Ideally the rule that encodes distance might use a look-up-table but because the size of this is unknown it might have to live in SDRAM, making it less ideal.  Hence the division is now replaced by reciprocal multiplication.

Remove gnu functions

---

spynnaker/pyNN/extra_algorithms/on_chip_bit_field_generator.py

Jobs where there are more machine graph vertices than application graph vertices were showing the following "error":
```
Running bitfield generation on chip
|0%                          50%                         100%|
===========================================================2020-09-07 09:36:17 ERROR: Too many update steps in progress bar! This may be a sign that something else has gone wrong!
=
```
which this hopefully fixes.
Tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/451

Fix progress bar "error"

---

neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c

this fixes the situation where the bitfield array (before any bitfields) cant be malloced (lack of dtcm, likely due to the master pop table being so big). This stops it from dabting, and allows the flow to keep operating. 
testing via : https://github.com/SpiNNakerManchester/sPyNNaker8/pull/443

fix for bitfields

---

spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py

SQLite and Numpy don't get on, so convert `numpy.int64` to `int` before creating the provenance item.

Don't log provenance data as BLOB!

---

spynnaker/pyNN/models/neuron/synaptic_manager.py
spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py

Currently spikes_per_tick is calculated differently in two diffrent places. UGLY!
Lets push the calc where it belongs.
Any fix to the calculation is out of scope of this PR.

use max_spikes_per_ts from spike_source_poisson

---

neural_modelling/src/synapse_expander/matrix_generator.c
neural_modelling/src/synapse_expander/matrix_generator.h
neural_modelling/src/synapse_expander/synapse_expander.c
spynnaker/pyNN/models/neuron/synaptic_manager.py

Found an example (thanks to @such-a-git) that doesn't work when using S1615 for scaling, so this switches to using U3232 instead.
Tested by (& merge with) https://github.com/SpiNNakerManchester/sPyNNaker8/pull/466

Switch scaling to using u3232 instead of s1615

---

spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py
spynnaker/pyNN/models/neural_projections/connectors/all_to_all_connector.py
spynnaker/pyNN/models/neural_projections/connectors/array_connector.py
spynnaker/pyNN/models/neural_projections/connectors/csa_connector.py
spynnaker/pyNN/models/neural_projections/connectors/distance_dependent_probability_connector.py
spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py
spynnaker/pyNN/models/neural_projections/connectors/fixed_probability_connector.py
spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
spynnaker/pyNN/models/neural_projections/connectors/index_based_probability_connector.py
spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
spynnaker/pyNN/models/neural_projections/connectors/multapse_connector.py
spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
spynnaker/pyNN/models/neural_projections/connectors/small_world_connector.py
spynnaker/pyNN/models/neuron/generator_data.py
spynnaker/pyNN/models/neuron/synapse_io.py
spynnaker/pyNN/models/neuron/synaptic_manager.py
spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py
spynnaker/pyNN/models/utility_models/delays/delay_generator_data.py
unittests/connector_tests/test_csa_connector.py
unittests/connector_tests/test_from_list_connector.py
unittests/model_tests/neuron/test_synaptic_manager.py
unittests/model_tests/test_connectors.py

The assumption that machine_vertex.app_vertex.vertex_slices[machine_vertex.index] == machine_vertex.vertex_slice will not hold when we move to splitter models that partition by different types of machine vertexes. Example synapse and neuron cores
This slightly slows down the MultapseConnector if there are a lot of machine vertexes but speeds up everything else as there are less parameters to pass around.
Tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/461

Slice index is not vertex index

---

spynnaker/pyNN/models/neural_projections/projection_application_edge.py
spynnaker/pyNN/models/neuron/synaptic_manager.py
unittests/model_tests/neuron/test_projection_application_edge.py
unittests/model_tests/neuron/test_synaptic_manager.py

In the past the slices came from the Applcation Vertex to be used in the SynampticManager calls.
But an ApplicationVertex could have multiple types of Vertexes with multiple sets of slices so wrong.
This saves the slice in the edge next to to SynampticManager 
Tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/463

Edge saves slices

---

spynnaker/pyNN/extra_algorithms/algorithms_metadata.xml
spynnaker/pyNN/extra_algorithms/spynnaker_machine_bit_field_router_compressor.py
spynnaker/pyNN/extra_algorithms/synapse_expander.py
spynnaker/pyNN/models/abstract_models/__init__.py
spynnaker/pyNN/models/abstract_models/abstract_synapse_expandable.py
spynnaker/pyNN/models/neuron/abstract_population_vertex.py
spynnaker/pyNN/models/neuron/population_machine_vertex.py
spynnaker/pyNN/models/utility_models/delays/__init__.py
spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py
spynnaker/pyNN/models/utility_models/delays/delay_extension_vertex.py

Changed synapse_expander to work at the machine level.
Created AbstractSynapseExpandable with the methods
gen_on_machine
read_generated_connection_holders
PopulationMachineVertex now has this api and methods
AbstractPopulationVertex no longer does
gen_on_machine moved from app to delay Machine level
aplx constants moved to the api, delay machine to highlight the relationship
BitField router compressor updated to only re expand when required.
tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/478

spynapse_expander at the machine level

---

unittests/model_tests/neuron/test_synaptic_manager.py

With https://github.com/SpiNNakerManchester/PACMAN/pull/312
It now matters if the app grpah not passed to the machine graph

all or nothing for machinevertex.appvertex

---

neural_modelling/src/bit_field_expander/bit_field_expander.c
neural_modelling/src/neuron/c_main.c
neural_modelling/src/neuron/population_table/population_table.h
neural_modelling/src/neuron/population_table/population_table_binary_search_impl.c

Reorder the loading of bitfields to be last.  This is needed because the pop_based_master_pop_table work accidentally reordered this, causing some scripts (e.g. microcircuit) to fail unexpectedly.
Tested by SpiNNakerManchester/sPyNNaker8#483

Reorder bitfield loading

---

spynnaker/pyNN/spynnaker_external_device_plugin_manager.py

Add partition_id as an argument to activate_live_output_to(...).

Allow specification of partition id for activating live output to

---

neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_recurrent_dual_fsm_impl.c
neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_recurrent_pre_stochastic_impl.c
neural_modelling/src/neuron/plasticity/stdp/timing_dependence/timing_vogels_2011_impl.c
neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_additive_one_term_impl.c
neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_additive_two_term_impl.c
neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_additive_two_term_impl.h
neural_modelling/src/neuron/plasticity/stdp/weight_dependence/weight_multiplicative_impl.c

Part of my long-term plan to expunge plain address arithmetic; part of what I was doing in #857

Use structures to describe STDP config

---

spynnaker/pyNN/models/neuron/master_pop_table.py

Found when running a structural plasticity example (working on adding examples to cover the remaining binaries in https://github.com/SpiNNakerManchester/sPyNNaker8/issues/484) that for some reason catches that this function isn't returning the index when it should be (I don't know why the current tests/examples aren't catching this...).
Tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/513

add_application_entry should return a value

---

neural_modelling/src/neuron/synapse_types/synapse_types_semd_impl.h
spynnaker/pyNN/models/neuron/builds/if_curr_exp_semd_base.py
spynnaker/pyNN/models/neuron/synapse_types/synapse_type_semd.py

Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/946.
Changes scaling_factor from a hard-coded value in C to a model parameter for sEMD.
Merge alongside https://github.com/SpiNNakerManchester/PyNN8Examples/pull/53
Tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/522

Make scaling_factor into a model parameter for sEMD

---

neural_modelling/src/neuron/input_types/input_type.h
neural_modelling/src/neuron/input_types/input_type_conductance.h
neural_modelling/src/neuron/input_types/input_type_current.h
neural_modelling/src/neuron/input_types/input_type_delta.h
neural_modelling/src/neuron/input_types/input_type_none.h

More cleaning up of compiler warnings - in this case, an example in the NewModelTemplate requires this struct parameter to be non-const as it allows it to be modified.
Merge alongside https://github.com/SpiNNakerManchester/sPyNNaker8NewModelTemplate/pull/64
Tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/525

input_type is not always const in this function (see example in NMT)

---

spynnaker/pyNN/models/neuron/master_pop_table.py
spynnaker/pyNN/models/neuron/synaptic_matrices.py

Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/892 (well, technically, it was already fixed, but this removes the fudge factors that are no longer being used after recent merges of master pop table updates, so this should close that issue).
Tested by https://github.com/SpiNNakerManchester/sPyNNaker8/pull/528

Remove unused OVERSCALE multipliers

---

spynnaker/pyNN/extra_algorithms/spynnaker_synaptic_matrix_report.py

Can't use %s any more in logging messages, switching to "... {} .. ".format(..) instead.

Replace %s with {} when using formatadapter during logging

---

.github/workflows/python_actions.yml

Documentation building is taking a long time (due to details of how `sphinx-apidoc` works). Split it into its own workflow so that we more clearly get the flake8/pylint results back in the GitHub UI.

Put doc builds in parallel with other validation

---

requirements.txt
setup.py

We can allow neo 9 as Channel index is still there.
another wart way improvement for https://github.com/NeuralEnsemble/PyNN/issues/708
tested with 
https://github.com/SpiNNakerManchester/IntegrationTests/tree/neo9
which has passed tests

Allow Neo9

---

.github/workflows/python_actions.yml

This PR halves the effective build time relative to its parent branch. This is why the jobs were parallel on `master` in the first place.
Timings (with 3.8):
| Phase | Timing (s) | Notes |
| - | - | - |
| Installation | 100 (~70 just for doc) | Shorter for doc-only because we can omit installing some things |
| Testing | 179 | Quicker without coverage, varies a lot between Python versions |
| Validation | 93 | Mostly (75%) due to pylint |
| Documentation | 350 | It's the running of `sphinx-apidoc` that's costly |
We can put the Documentation build in parallel (i.e., as a separate build job) to the Testing and Validation, and it will reduce our total elapsed wall-clock build times by around 4&half; minutes (estimated 179+93=272 seconds). Once I figure out how to make Sphinx go faster, we …

Restore doing the (very slow!) doc builds in parallel with testing

---

.github/workflows/publish.yml
.github/workflows/python_actions.yml

Because “`Beginning with Matplotlib 3.4, Python 3.7 or above is required.`” and it is a transitive dependency of pynn, which doesn't version its requirement there.

We need to use today's new special matplotlib trickery

---

.github/workflows/python_actions.yml
doc/source/conf.py

The problem with the slow documentation building was because the apidoc preparation code was finding lots of irrelevant files (notably in the `.git` directory!) that was hugely extending the list of things to filter out unnecessarily.
Once some other minor issues are sorted, this will enable merging the doc building into the main workflows.

Much faster documentation building

---

requirements.txt

replaces previous Pr that tried this.
Matplotlib not added to setup.py as that has caused more issues than it fixed in the past.

cap matplotlib and remove duplicate quantites

---

neural_modelling/makefiles/neuron/neural_build.mk
neural_modelling/src/neuron/implementations/neuron_impl_external_devices.h
neural_modelling/src/neuron/implementations/neuron_impl_standard.h
neural_modelling/src/neuron/synapse_types/synapse_types.h
neural_modelling/src/neuron/synapse_types/synapse_types_alpha_impl.h
neural_modelling/src/neuron/synapse_types/synapse_types_delta_impl.h
neural_modelling/src/neuron/synapse_types/synapse_types_dual_excitatory_exponential_impl.h
neural_modelling/src/neuron/synapse_types/synapse_types_exponential_impl.h
neural_modelling/src/neuron/synapse_types/synapse_types_semd_impl.h

Fix https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/757
I guess this turned into something else on further inspection - the global variables used in synapse_types.h etc. are unnecessary and can be turned into pass-through variables instead.
Merge with https://github.com/SpiNNakerManchester/sPyNNaker8NewModelTemplate/pull/69
Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/21

remove unnecessary references from neural_build.mk

---

p8_integration_tests/quick_test/test_connectors/test_from_list_connector_mixed.py
spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py

Deal with the case where weights / delays are not given in a FromListConnector and are specified using RandomDistribution in the StaticSynapse.
Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/22

Deal with cases with mixed list and RandomDistribution, add tests

---

neural_modelling/src/neuron/implementations/neuron_impl_external_devices.h

A couple of global parameters are no longer used in the external devices impl (caught by the compiler), so this PR removes them.
Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/24

These globals are no longer used in this impl

---

p8_integration_tests/quick_test/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_200n_100pc_with_delays_all_recording.py
p8_integration_tests/quick_test/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_delays_delay_extensions_all_recording.py
p8_integration_tests/quick_test/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_delays_no_delay_extension_all_recording.py
p8_integration_tests/quick_test/test_param_vertex_retrieval_from_board_after_1_run/test_synfire_20n_20pc_no_delays_all_recording.py
p8_integration_tests/quick_test/test_selective_recording/test_recording_on_off.py

No need to do os.path.join(current_file_path....
as BasteTestCase setup() changes directory into the current directory so the paths can be relative.

No need for current_file_path as BaseTestCase cd into it

---

spynnaker/pyNN/abstract_spinnaker_common.py
spynnaker/pyNN/models/neuron/synaptic_matrix_app.py

doing projection get weight both before and after run cause the before run to be returned both times.
This was due to SynapticMatrix caching the read values.
Fix 1. Clear the cache after reading pre data
Fix 2. Clear all caches after run so get reads in fresh data
Implemented both to be safe.

Clear cache

---

spynnaker_integration_tests/test_various/test_record_packets_per_timestep.py

Add a test for the output of pop.record("packets-per-timestep").

Add test for output of record("packets-per-timestep")

---

spynnaker_integration_tests/test_iobuf/test_iobuf_without_during_run_flag/spynnaker.cfg

found another dead cfg option in tests

read_router_compressor_with_bitfield_iobuf  no longer used.

---

neural_modelling/src/synapse_expander/param_generators/param_generator_normal_clipped.h
spynnaker_integration_tests/test_various/test_synaptic_expander.py

Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/1044
Adds a test to check that an error is thrown based on the example given in the issue.
Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/56

Error when too many redraws are requested in a clipped distribution

---

spynnaker/pyNN/extra_algorithms/spynnaker_neuron_network_specification_report.py
spynnaker/pyNN/spynnaker.cfg
unittests/test_using_virtual_board/test_debug_mode/spynnaker.cfg
unittests/test_using_virtual_board/test_debug_mode/test_debug.py

When using png on large files it reports
"graph is too large for cairo-renderer bitmaps"
The resulting svg file is USELESS. In the extreme cases just some gray shading.
Not sure about the cutoff

use svg for big files in SpYNNakerNeuronGraphNetworkSpecificationReport

---

neural_modelling/src/neuron/synapses.c

Discovered this on the CurrentSource branch - an error is logged but then no return takes place, so the code tries to carry on and hangs.

Return false after logging error

---

spynnaker/pyNN/models/projection.py

Fix for master: new pylint version does not appear to like including functions that aren't implemented when they should return values / objects.

Remove functions that aren't implemented so don't return anything

---

spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
spynnaker/pyNN/models/neural_projections/connectors/array_connector.py
spynnaker_integration_tests/test_array_connector/test_array_connector.py

The maximum calculations in the ArrayConnector were wrong (they should be per neuron, not per slice) and so errors were being thrown where they shouldn't have been.  I've also adjusted the descriptions for the relevant functions in the AbstractConnector to hopefully make it a bit clearer what these functions are doing.

Fix array_connector max calculations

---

spynnaker_integration_tests/test_external_devices/test_live_sync.py

On master from home with spalloc
and on on executor jenkins
There where times when the send_syn fired twice between recv calls

allow for mutliple send_sync

---

spynnaker_integration_tests/test_multi_call_examples/test_reset_new_pop.py

In https://github.com/SpiNNakerManchester/sPyNNaker/pull/1127 we made sure that am empty segment is added even if there is not data.
This test has an edge case where the second population is only created after the sim.reset.
For constancy agreed with @rowleya that for constancy all Populations will always have the same number of segments.  
Except of course those that never record and so have none)
This pr fixes a test that was based on the old behaviour

all populations have the same number of segments

---

spynnaker/pyNN/abstract_spinnaker_common.py

To make sure we add a CommandSender afer a hard reset we turned of caching.
This breaks the adding of a user CommandSender.
As @rowleya did not know any use case we have disabled the users ability to add one.

disable user CommandSender

---

spynnaker/pyNN/spynnaker_external_device_plugin_manager.py
spynnaker_integration_tests/test_external_devices/test_live_spike_translator.py

Update to make use of Key Translation from SpiNNakerManchester/SpiNNFrontEndCommon#901 and add an example.

Key translation

---

requirements.txt

Mainly a test for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/905
Removes the last direct reference to scipy

scipy from FEC (which caps)

---

spynnaker/pyNN/models/common/neuron_recorder.py
spynnaker_integration_tests/test_various/test_record_packets_per_timestep.py

Discovered while running other code that packets-per-timestep recording was broken for multi-run; this fixes it and adds a test for multi-run recording with packets-per-timestep.
Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/95

Multirun packets-per-timestep fix

---

spynnaker/pyNN/models/projection.py

ApplicationGraph currently track _outgoing_edge_partitions_by_pre_vertex and _incoming_edges
the partitions are used in several places.
The edges only by the method
graph.get_edges_ending_at_vertex
This removes the only know use of get_edges_ending_at_vertex (other than tests)
This allows the removal of a defaultdict(OrderedSet) in Graph which is filled in even for none PyNN usages.

Use outgoing_edge_partitions to find edge

---

spynnaker/pyNN/models/populations/population.py
spynnaker/pyNN/models/populations/population_view.py
spynnaker/pyNN/models/recorder.py
spynnaker_integration_tests/test_views/test_views.py
spynnaker_integration_tests/test_views/test_views_data.py

spinnaker_get_data now has an extra optional bool param as_matrix
If set will return V as a 2d matric ids * timestamps, (Without headers)
spinnaker_get_data enabled on views
better error with spinnaker_get_data("rewirings")
remove message that spinnaker_get_data may not be supported.

spinnaker_get_data

---

spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_slice.py
spynnaker/pyNN/extra_algorithms/splitter_components/splitter_delay_vertex_slice.py
spynnaker/pyNN/models/populations/population.py
spynnaker/pyNN/spinnaker.py
unittests/test_using_virtual_board/test_max_cores.py

Part of https://github.com/SpiNNakerManchester/PACMAN/pull/433
Fixes:
https://github.com/SpiNNakerManchester/sPyNNaker/issues/1182
by warning that it will not affect already created Populations
We currently dont support the raising of 
sim.set_number_of_neurons_per_core
Mainly because I was too lazy to work out how to get and check the model hard cap
And there was no known need for it.
beyond the model cap give a clear error that is not allowed
higher than a previously lower value give an error that we dont allow that at the moment
pop.set_max_atoms_per_core
can now also raise a previously lowered value but only up to the cap for that model.
That is both the model hard cap and the sim.set_number_of_neurons_per_core soft cap.

app vertex max_atoms_per_core

---

neural_modelling/src/neuron/spike_processing_fast.c
spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_neurons_synapses.py
spynnaker/pyNN/models/neuron/population_synapses_machine_vertex_common.py

Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/1186 for both neuromodulated and non-neuromodulated STDP.
[Previous comment: Discussions of https://github.com/SpiNNakerManchester/sPyNNaker/issues/1186 via Skype highlighted that there were also problems with non-neuromodulated STDP on self-projections.  This fixes those cases but there still remain issues when the STDP is neuromodulated, for which discussions and investigations are ongoing.]
Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/122

Allow STDP on self-projections

---

requirements.txt

Matplotlib version needs to be limited for python 3.7, see e.g. https://github.com/SpiNNakerManchester/PyNN8Examples/runs/7999013468?check_suite_focus=true

Fix version of matplotlib for python 3.7

---

spynnaker/pyNN/models/spike_source/spike_source_array_vertex.py
unittests/model_tests/neuron/test_spike_source/test_spike_source_array_vertex.py

With a SSA we know in advance how many spikes are send.
Se we can warn the users.
Most common cause is likely to be
1. A mutli neuron SSA with a single list and then a OneToOne
Where a single Neuron SSA and an AllToAll have the same affect
2. Random generated lists.
This simplified version does not consider how the spike source could be partitioned as that only reduces spikes received by the target if filtering is done.
This version does not consider timescale factor to determine the warning cutoff.

Warning if SpikeSourceArray sends more that 100 spikes at one time.

---

spynnaker/pyNN/models/spike_source/spike_source_array_vertex.py

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
note:
init converts None spike_times to an empty list
@spike_times.setter did and still does not

need len for some versions of numpy

---

spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_fixed.py
spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_neurons_synapses.py
spynnaker/pyNN/models/neuron/population_machine_synapses.py
spynnaker/pyNN/utilities/bit_field_utilities.py

This avoids reusing incoming_projections to make sure that iterations over projections actually happen in all cases.
Tested by SpiNNakerManchester/IntegrationTests#148

Iterate projections

---

spynnaker/pyNN/extra_algorithms/splitter_components/splitter_abstract_pop_vertex_neurons_synapses.py
spynnaker_integration_tests/test_split_various/test_split_sdram.py

SDRAM bug found when trying to use splitters with the cerebellum network as it currently stands.
The test included here is a simplified version of the problem found which (on current master) results in the exception:
`
Exception: Too much SDRAM has been allocated on chip 0, 0:  129711198 of 123469792`
(Note: the cerebellum network currently uses FromList connectors; I've used an AllToAll here to simplify the script so it runs faster than having to load in a cerebellum-like FromList).
Tested by https://github.com/SpiNNakerManchester/sPyNNaker/pull/1241

Fix SDRAM calculation on neurons-synapses splitter, add test

---

spynnaker_integration_tests/test_local_only/test_overlapping_network.py

Work around to stop https://github.com/SpiNNakerManchester/sPyNNaker/issues/1261 breaking tests
tested by http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/skip_missing_fpga/1/pipeline

skip on missing fpga link

---

neural_modelling/src/neuron/c_main_neurons.c
neural_modelling/src/neuron/structural_plasticity/synaptogenesis/sp_structs.h

Building code with -Werror just to catch some (recent) warnings that had crept in, some are only found by gcc v12 but others existed in gcc v9.  One warning found further down the toolchain which I suggest we don't (yet) fix is described at https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/issues/1013.
[I suggest we probably leave -Werror out of the default (user) build in automatic_make as we don't necessarily want to force people to use a particular version of gcc, though perhaps it might be a nice idea to have it somewhere in a build process that gets used in CI?]
Will test this branch once the big machine is back up and running again; for now scripts related to where changes were made seem to be working locally at least.

Tidy up code with warnings in gcc v12.2

---

neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_izhikevich_neuromodulation.c
neural_modelling/src/neuron/plasticity/stdp/synapse_dynamics_stdp_mad_impl.c
neural_modelling/src/neuron/synapses.c

The check against the colour_delay wasn't quite right, and skipped synapses were not being calculated in the stdp mad impl.
Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/171
(Doesn't depend on https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1011 necessarily but gave the branches the same name for testing purposes).

Apply delay check correctly and increment skipped in mad impl

---

spynnaker/pyNN/models/common/neuron_recorder.py
spynnaker_integration_tests/test_selective_recording/test_sampling.py

Fix for: https://github.com/SpiNNakerManchester/sPyNNaker/issues/1274
Easiest was to tell the cores where no neurons where recording that the recording rate was zero.
Used the new _rate_and_count_per_slice for both sdram sizes and data spec to make sure they same in sync 
Simplified the if variable in self.__bitfield_variables
as most of the code was them same.
Added a new test which was broken before the fix.
manually tested the no generate on machine by
tweaking the neuron_data generate_on_machine method to just return False
https://github.com/SpiNNakerManchester/sPyNNaker/blob/0a6621814128e839f9ec8cb8a592208077a6917f/spynnaker/pyNN/models/neuron/neuron_data.py#L100
tested by:
http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/rate_and_count_per_slice/1 …

rate_and_count_per_slice

---

spynnaker/pyNN/utilities/neo_buffer_database.py
spynnaker_integration_tests/test_various/test_clear.py
spynnaker_integration_tests/test_various/test_clear_rewires.py

there where three bugs in the pop.get_data clear=True.
1. Did not handle the case of a single variable or "all"
2. Did not change the recording start time.
3. The event time incorrectly added t_start
this PR fixes those bugs and adds tests
tested by 
http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/clear/1/pipeline/16

fix Clear bug

---

spynnaker/pyNN/models/neuron/plasticity/stdp/timing_dependence/timing_dependence_pfister_spike_triplet.py
spynnaker_integration_tests/test_stdp/test_STDP_triplet_additive.py

An incorrect size value in the STDP triplet timing rule was causing the weights to be read incorrectly at the end of a run.  This fixes the problem and adds a test to make sure we don't get caught out by this again in the future.

Fix STDP triplet rule and add test

---

spynnaker/pyNN/models/recorder.py
spynnaker/pyNN/utilities/neo_buffer_database.py
spynnaker_integration_tests/test_various/test_clear.py

For the record I hate get_data clear!
I would rather log warn that we ignore the setting!
I would rather support the ability to get a time subset of data out of the database
Well if we must this now support get_data clear =True on a previous segment
Fixes https://github.com/SpiNNakerManchester/sPyNNaker/issues/1249
also a quick change to support
pop.record["all"])

fix getdata clear on previous segment Clear

---

spynnaker/pyNN/external_devices_models/push_bot/parameters/push_bot_retina_viewer.py
spynnaker/pyNN/external_devices_models/push_bot/spinnaker_link/push_bot_retina_device.py

Changes to the pushbot viewer that make it work better.  Also lets the pushbot retina input be divided into multiple source cores (depends on SpiNNakerManchester/PACMAN#501 to avoid crashes)

Push bot viewer

---

spynnaker/pyNN/setup_pynn.py

Don't ever need to set up on RTD, make it a direct-run-only script (it makes little sense to do the setup immediately when using as a library), and factored out the target PyNN version so that we only need to set it in one place

Make the code in setup_pynn better

---

setup.cfg
spynnaker/pyNN/models/populations/population.py
spynnaker/pyNN/models/populations/population_view.py
spynnaker/pyNN/utilities/data_population.py
spynnaker/pyNN/utilities/neo_compare.py
spynnaker/pyNN/utilities/neo_convertor.py
spynnaker/pyNN/utilities/neo_csv.py
spynnaker/pyNN/utilities/utility_calls.py
spynnaker_integration_tests/scripts/pattern_spiker.py
spynnaker_integration_tests/test_selective_recording/test_thritytwo.py
unittests/test_pop_views_assembly/test_data_population.py
unittests/test_pop_views_assembly/test_getting.py

This Pr switches to using PyNN 0.11 instead of the previously supported PyNN 0.9.1
Remember we could not use 0.10 due to a bug in the plotting code.
The critical change is that Neo AnnalogSignal no longer has a channel_index
To get the index an Analog signal covers instea of doing
v.channel_index.index
do 
v.annotations["channel_names"]
There was a minor bug  in the latest neo
https://github.com/NeuralEnsemble/python-neo/issues/1287
a small work around has been provided in Utils
So instead of
neo.get_io("filetowriteto.pkl")
do
from spynnaker.pyNN.utilities.utility_calls import get_neo_io
get_neo_io("filetowriteto.pkl")
Note this is only needed for NOT existing files. Ie before a write call
This change BREAKS usage of PyNN 0.9.1 due to pyNN/utility/plotting
see: …

Switch to PyNN 0.11.0

---

spynnaker_integration_tests/test_debug_mode/check_debug.py
spynnaker_integration_tests/test_power_monitoring/spynnaker.cfg
unittests/test_using_virtual_board/test_debug_mode/test_debug.py

remove unused cfg flag
same as https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1067
http://apollo.cs.man.ac.uk:8080/blue/organizations/jenkins/Integration%20Tests/detail/write_provenance_data/3/pipeline

write_provenance_data no longer used

---

spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
spynnaker_integration_tests/test_spike_source/test_poisson_spike_source.py

The included test fails on the master branch because the region size calculation doesn't take into consideration that the set rate values may change from being the same to being different on a subsequent call to run().  This branch fixes the issue by assuming all the rates are different, though there may be a better way of doing it... ?
Tested by https://github.com/SpiNNakerManchester/IntegrationTests/pull/216

Fix poisson multirun error

---

setup.cfg

https://pypi.org/project/PyNN/0.12.0/ is missing a dependency
This is actively been worked on see: https://github.com/NeuralEnsemble/PyNN/issues/788
Other changes to PyNN between 0.11 and 0.12 do not appear to affect Spynnaker
Test with adding a version of the missing dependency https://github.com/SpiNNakerManchester/sPyNNaker/pull/1390
This pr therefor blocks the unlucky version without excluding later ones.

block broken PyNN 0.12.0 version

---

spynnaker/pyNN/utilities/struct.py

This only shows up when you have a single global parameter (or maybe more global that not).

Fix issue with neuron generation global parameters

---

spynnaker_integration_tests/test_0_1_time_steps/test_allow_violate/test_allow.py

Found by type Checking branches
unittest.SkipTest must have a reason
so raise_skiptest must have one too
part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/248

SkipTest must have a reason

---

spynnaker/pyNN/models/neuron/population_machine_common.py
spynnaker/pyNN/models/neuron/population_machine_neurons.py
spynnaker/pyNN/models/neuron/population_machine_synapses.py
spynnaker/pyNN/models/neuron/population_machine_synapses_provenance.py
spynnaker/pyNN/models/neuron/population_machine_vertex.py
spynnaker/pyNN/models/neuron/population_neurons_machine_vertex.py
spynnaker/pyNN/models/spike_source/spike_source_array_machine_vertex.py
spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
spynnaker/pyNN/models/utility_models/delays/delay_extension_machine_vertex.py

PopulationMachineNeurons and PopulationMachineSynapses have @abstractproperty
_app_vertex and _vertex_slice
It picked these up from MachineVertex but not because MachineVertex implemented the properties but because these names where in MachineVertex's slots.
UGLY!
To make it worse Typing does not support @abstractproperty instead requiring  @property @abstractMethod.
So instead of also implementing _app_vertex and _vertex_slice better to use the unprotected methods!
The rest of the protected abstract are less of an issue as the Super classes of PopulationMachineNeurons implement these as methods already. 
PopulationMachineSynapsesProvenance also defined _app_vertex but never uses it!
PopulationMachineVertex could use the slots value (_vertex_slice) as it is a superclass but using the …

Use app_vertex and vertex_slice

---

spynnaker/py.typed
spynnaker/pyNN/models/neural_projections/connectors/abstract_connector.py
spynnaker/pyNN/models/neural_projections/connectors/abstract_generate_connector_on_machine.py
spynnaker/pyNN/models/neural_projections/connectors/connection_types.py
spynnaker/pyNN/models/neural_projections/connectors/from_list_connector.py
spynnaker/pyNN/models/neural_projections/connectors/kernel_connector.py
spynnaker/pyNN/models/neural_projections/synapse_information.py
spynnaker/pyNN/models/neuron/local_only/abstract_local_only.py
spynnaker/pyNN/models/neuron/local_only/local_only_convolution.py
spynnaker/pyNN/models/neuron/local_only/local_only_pool_dense.py
spynnaker/pyNN/models/neuron/synapse_dynamics/__init__.py
spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics.py
spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_neuromodulation.py
spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_static.py
spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py
spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_stdp.py
spynnaker/pyNN/types.py
unittests/connector_tests/test_weights_delays_connector.py
unittests/model_tests/neuron/synapse_dynamics/__init__.py
unittests/model_tests/neuron/synapse_dynamics/test_abstract_synapse_dynamics.py
unittests/model_tests/neuron/test_synapse_io.py

The types (as defined by PyNN) that we have to accept or weight and  delay are rather messy.
This PR checks the types and improves the Exceptions.
Changes include
1. py.typed file to tell the type checker to look for types
2. PyNN.types.py file to hold the type declarations in a single place
- includes an is_scaler method which includes a TypeGuard
3. Methods to create more informative Exceptions (in AbstractConnector)
4. Pushing of holding the delay and weight into AbstractWeight
- Allows converting the many inputs into a smaller known subset
- Allows checking to types. (These methods could be commented out after all tests pass)
5. As we know multiple weights are converted to numpy.arrays the check len has been replaced by is-instance.
- required because str has len
7. Adds some tests …

Typing and better errors for delay and weights

---

.github/workflows/c_actions.yml
.github/workflows/python_actions.yml
doc/source/conf.py
setup.cfg
setup.py
spynnaker/pyNN/models/neural_projections/connectors/pool_dense_connector.py
spynnaker/pyNN/models/spike_source/spike_source_poisson_machine_vertex.py
spynnaker/pyNN/models/spike_source/spike_source_poisson_vertex.py
spynnaker/pyNN/setup_pynn.py

part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/260

Python3.12

---

.github/workflows/c_actions.yml
.github/workflows/python_actions.yml
proxy_integration_tests/__init__.py
proxy_integration_tests/test_python_debug/__init__.py
proxy_integration_tests/test_python_debug/check_debug.py
proxy_integration_tests/test_python_debug/spynnaker.cfg
proxy_integration_tests/test_python_debug/test_debug.py

The main purpose here is to have github actions run an actual job using spalloc proxy.
The c build action has been changed
- some reordering
- download the FEC binaries, PyNN binaries and the log.sqlite3 file
Then a new job has been added which runs an actual job on an actual machine
- uploads the above files to a  external_binaries directory
- add a cfg settings to say where these files are.
- tests the newly added proxy_integration_tests
The first integration test is a very simple graph but in debug nodes so all reporting is tried.
Note the spynnaker_neuron_graph_network_specification_report will raise a caught exception in Windows and macos as installing the graphviz on these platforms was considered out of scope for a rarely used report.
These Support script/ yml files are a key part …

runs an intergation test in linux, windows and macos

---

spynnaker/pyNN/spynnaker.cfg
spynnaker_integration_tests/test_debug_mode/test_java_debug/spynnaker.cfg

part of https://github.com/SpiNNakerManchester/SpiNNUtils/pull/274
depends on https://github.com/SpiNNakerManchester/sPyNNaker/pull/1459

Cfg checker

---

spynnaker/pyNN/data/spynnaker_data_view.py
spynnaker/pyNN/utilities/neo_buffer_database.py
unittests/data/test_simulator_data.py

Alternative to https://github.com/SpiNNakerManchester/sPyNNaker/pull/1464
Keep the safety check but use sets.
This comes at the expense of none repeatable order.
The only place I found where this matters is in the data.ds
So fixed the order by used in the get method

Sets for speed

---

spynnaker/pyNN/models/neuron/abstract_population_vertex.py

a better error message for https://github.com/SpiNNakerManchester/sPyNNaker/issues/1468
In most coses we can handle many more that 1000 incoming projections but at that number the error makes sense

Better error

---

spynnaker/pyNN/__init__.py

Mainly to explain the message:
WARNING: A timestep was entered that has forced SpiNNaker to automatically slow the simulation down from real time by a factor of 10.

a warning for default/None timestep

---

neural_modelling/makefiles/neuron/IF_curr_exp_weight_change/Makefile
neural_modelling/makefiles/neuron/Makefile
neural_modelling/makefiles/neuron/neural_build.mk
neural_modelling/src/neuron/plasticity/weight_change/post_events_with_weight_change.h
neural_modelling/src/neuron/plasticity/weight_change/synapse_dynamics_external_weight_change.c
neural_modelling/src/synapse_expander/matrix_generator.c
neural_modelling/src/synapse_expander/matrix_generators/matrix_generator_stdp.h
neural_modelling/src/synapse_expander/matrix_generators/matrix_generator_weight_changer.h
spynnaker/pyNN/extra_models/__init__.py
spynnaker/pyNN/models/neuron/synapse_dynamics/__init__.py
spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_generate_on_machine.py
spynnaker/pyNN/models/neuron/synapse_dynamics/abstract_synapse_dynamics.py
spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_stdp.py
spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_static.py
spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_structural_stdp.py
spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_weight_changable.py
spynnaker/pyNN/models/neuron/synapse_dynamics/synapse_dynamics_weight_changer.py
spynnaker/pyNN/models/projection.py
spynnaker_integration_tests/test_various/test_weight_changer.py

Allow an external weight change from a different connection.  This is a bit like STDP with neuromodulation, but much simpler.  A projection can be "WeightChangable" which is the "STDP" part.  This can then also have a "WeightChanger" projection which is like the neuromodulation; this takes the WeightChangable projection as a parameter, and the source Population must have the same number of neurons as the Projection it affects, and must of course target the same target Population and receptor type (this is checked).  The WeightChanger connections are then set up so that they affect a specific pre-post pair of neurons.  When the Pre-Population of the WeightChanger spikes, the weight is changed by the specified amount (which can be positive or negative) on any connection that matches the …

External weight change

---

spynnaker/pyNN/models/recorder.py
spynnaker/pyNN/utilities/neo_buffer_database.py
spynnaker_integration_tests/test_various/test_recording_later_additions.py
unittests/test_pop_views_assembly/test_csv.py

fixes a big with write csv data when recording is started after a reset.
Set write data to act like get data
- previous segments may be empty
- previous segments may miss some variables
- get/write after a reset 
. fails if no previous data,
. return previous data
. does NOT check if all requested variables are set to record.
- get spike counts never includes previous data so fails after a rest
fixes the test by
- Deleting csv files from previous runs
- Added more checks on behaviour

Csv write fix

---

spynnaker/pyNN/models/neural_projections/connectors/one_to_one_connector.py
unittests/model_tests/neuron/test_synaptic_manager.py

Minor change of order that helps the one-to-one performance when there are not multiple dimensions

Fix one to one performance

---

spynnaker/pyNN/external_devices_models/spif_output_device.py
spynnaker/pyNN/models/neuron/abstract_population_vertex.py

part of https://github.com/SpiNNakerManchester/PACMAN/pull/585

Typing for PACMAN

---

unittests/test_using_virtual_board/test_none_defaults/spynnaker.cfg
unittests/test_using_virtual_board/test_none_defaults/test_simple.py

test for https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1244
Only failed i(None spalloc issues) in the microcircuit_model Integration Tests
This was because that was the first place the none default
use_auto_pause_and_resume = False
was used.
This adds a test with many of the cfg default values inverted.
the above pr failed this test until fixed,

Test None default cfg

---

spynnaker_integration_tests/test_external_devices/test_spike_run_forever_again.py

tests https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon/pull/1237

test ssa in forever mode

---

spynnaker/pyNN/models/abstract_pynn_model.py
spynnaker/pyNN/models/defaults.py

Both our implementations of PyNN models default parameters have the disadvantage that they return a dict which appears mutable but that these changes do not affect future init of that model.
The method using spynnaker/pyNN/models/defaults.py is both neater and considerably easier to type!
This pr makes these methods return a immutable Mapping so if the user does something we do not support it fails fast

Imutable defaults

---

spynnaker/pyNN/external_devices_models/munich_spinnaker_link_motor_device.py
spynnaker/pyNN/models/abstract_pynn_model.py
spynnaker/pyNN/models/defaults.py
spynnaker/pyNN/models/neural_projections/connectors/one_to_one_offset_connector.py
spynnaker/pyNN/models/neuron/builds/eif_cond_alpha_isfa_ista.py
spynnaker/pyNN/models/neuron/builds/hh_cond_exp.py
spynnaker/pyNN/models/neuron/builds/if_cond_alpha.py
spynnaker/pyNN/models/neuron/builds/if_facets_hardware1.py
unittests/model_tests/neuron/test_abstract_neuron_impl.py
unittests/model_tests/neuron/test_defaults.py
unittests/test_populations/test_vertex.py

In master there are two ways that the decorators @default_parameters and @default_initial_values are converted to a mapping of the values in the init.  Making these properties
@defaults
This calculated the mappings when the class is imported (even if not used)
The resulting mapping replace the calculate functions so the calculation is only done once!
This style also did not have properties for mypy to find 
AbstractPyNNModel
This calculated the mapping every time the property was called
Only worked for classes that extended AbstractPyNNModel
This PR merges the best of both solutions into AbstractProvidesDefaults
AbstractPyNNModel and any class which used to be decorated by @defaults now extends AbstractPyNNModel
The calculation of the mappings is delayed until either property is used. …

Abstract provides defaults

---

spynnaker/pyNN/external_devices_models/push_bot/parameters/push_bot_retina_viewer.py

PushBotRetinaViewer took the pyNN.spiNNaker module as an import
This was ugly (and would have been hard to type.)
replaced with some direct imports
end and run had to be delayed imports to avoid the circular monster
left sim as a parameter (now ignored) for reverse compatibility

don't pass a module as a parameter

---

spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py
spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py

Ignores:
spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py:179: error: Argument 1 to "savetxt" has incompatible type "TextIOWrapper[_WrappedBuffer]"; expected "str | PathLike[str] | str | PathLike[str] | SupportsWrite[bytes] | SupportsWrite[bytes]"  [arg-type]
spynnaker/pyNN/models/neural_projections/connectors/fixed_number_pre_connector.py:186: error: Argument 1 to "savetxt" has incompatible type "TextIOWrapper[_WrappedBuffer]"; expected "str | PathLike[str] | str | PathLike[str] | SupportsWrite[bytes] | SupportsWrite[bytes]"  [arg-type]
spynnaker/pyNN/models/neural_projections/connectors/fixed_number_post_connector.py:179: error: Argument 1 to "savetxt" has incompatible type "TextIOWrapper[_WrappedBuffer]"; expected "str | PathLike[str] | str | …

  # type: ignore[arg-type]

---

spynnaker/pyNN/models/neuron/synaptic_matrices.py
unittests/model_tests/neuron/test_synaptic_manager.py

numpy can not compare an unit32 and a Decimal.
import numpy
from decimal import Decimal
ni = numpy.array([1])
nf = numpy.array([1.0])
d = Decimal("4294967295.99999999976716935634613037109375")
print(min(d, nf[0]))
print(min(d, ni[0]))
print(min(nf[0], d))
print(min(ni[0], d))
gives:
1.0
1
1.0
Traceback (most recent call last):
File "/home/brenninc/spinnaker/my_spinnaker/test.py", line 9, in <module>
print(min(ni[0], d))
TypeError: argument must be an integer

invert the order in min as numpy uint32 cries if the second is not an int

---

spynnaker/pyNN/data/spynnaker_data_view.py
spynnaker/pyNN/models/populations/population.py
spynnaker_integration_tests/test_external_devices/test_live_sync.py

sim.set_number_of_neurons_per_dimension_per_core only affects Populations not yet made.
So add a warning if used after Populations have been made.
Also moves the requires Mapping on a set_max_atoms_per_dimension_per_core to the Pacman Level
See https://github.com/SpiNNakerManchester/PACMAN/pull/594

a warning if calling sim.set_number_of_neurons_per_dimension_per_core

---

spynnaker/pyNN/models/neuron/population_machine_vertex.py
spynnaker/pyNN/models/neuron/population_neurons_machine_vertex.py
spynnaker/pyNN/models/neuron/population_synapses_machine_vertex_common.py
spynnaker/pyNN/models/neuron/population_vertex.py

Adds some checks to avoid trying to use binaries that don't exist.  Note that this will run a joined core at 0.1ms in realtime if that is the only thing it has to hand, and produce a warning in that case.
Tested with:
- SpiNNakerManchester/IntegrationTests#320

Better automatic split cores
